### ISSUE TITLE
Decouple AmazonS3Resolver & AmazonS3Cache from Amazon

### ISSUE THREAD

**Issue by jameskennard** [medusa-project/cantaloupe#106]
Hi,

I'm trying to use Cantaloupe with [Minio](https://www.minio.io/) (an S3 compatible Object Store). I've had to make some minor additions to get this to work for Cantaloupe 3.3:
* Use Path Style
* Disable Chunked Encoding

When constructing the `AmazonS3` client object it comes with a pre-configured `S3ClientOptions` with defaults from the AWS S3 SDK. It was necessary to override these.

Here are the changes: https://github.com/jameskennard/cantaloupe/commit/9c4bcaa565432e8792c08fcdbf17fed00b31ad38

Are these changes something you would be interested in incorporating if I were to make similar changes to develop and raise a Pull Request?

I have noticed that Cantaloupe 3.3 includes the ability to configure an alternative S3 Endpoint. This appears to have been removed from develop. This is required in order to use Minio instead of S3.

Thanks

James.

**Comment by adolski** [comment]
I think this would make a fine addition to 3.4. There have been some changes to the S3 stuff in 3.4-SNAPSHOT (`develop` branch) including an updated S3 client and an e.i.l.c.util.AWSClientFactory shared by AmazonS3Resolver and AmazonS3Cache. That class might need some changes to its constructors to better accommodate these new options.

`ENDPOINT_CONFIG_KEY` is vestigial; I think I was thinking about using it a long time ago for testing but then didn't. But, feel free to make use of it.

I would like to include the same improvements to AmazonS3Cache, and then all of the new config keys will need to be added to the sample config file, admin interface, and upgrading page, but I'm happy to do all of that myself.

**Comment by jameskennard** [comment]
That's great, I will look into creating a Pull Request in due course.

Thanks!

**Comment by jonathangreen** [comment]
Just chiming in here to say this would be useful to me as well. I want to use Cantaloupe eventually to connect to the Softlayer S3 compatible storage, and I'll need these options to do so.

**Comment by adolski** [comment]
I have this working now. It's rather disruptive (some renamings and config key changes -- see the [upgrade guide](https://github.com/medusa-project/cantaloupe/blob/feature/s3endpoints/website/upgrade.html)) so I've left it in `feature/s3endpoints` for the time being; will merge into `develop` sooner or later.

All the tests pass against Minio except two in S3CacheTest -- not sure what's going on there, but the same tests pass against AWS S3, so I've left them as-is for the time being.

**Comment by jameskennard** [comment]
Thank you for looking into this. Apologies for not getting round to creating a PR myself. Just reading through the upgrade guide and it sounds sensible, really like the fact you have removed Amazon from the key names. This makes clear that you can use it with other S3 vendors.

James.

**Comment by adolski** [comment]
No problem @jameskennard!

It's merged now.

**Comment by jameskennard** [comment]
Hi,

Have been testing the changes connecting to a Minio S3 server, and everything is looking really good. Great work! Would love to get this into our production environments at some point. Do you have any thoughts as to when the next release will be?

Thanks

James

**Comment by adolski** [comment]
Good to hear!

I don't know when the 4.0 release will be -- maybe summer, give or take.

**Comment by jameskennard** [comment]
Looking forward to it. Will keep an eye out for the release. I spotted the 4.0 Milestone after I commented, and can see there are more good things to come for 4.0.

Thanks

James.
