### ISSUE TITLE
Question about direct file access

### ISSUE THREAD

**Issue by RussellMcOrmond** [medusa-project/cantaloupe#110]
We will be replacing an existing content server with Canataloupe.  I'm am looking for advise for some of the additional features we need to implement.

Our existing server does 3 things:

* Provide access to image derivatives (source is jpeg, jpeg2000, tiff, pdf), which is what the IIIF interface in Cantaloupe does
* Provide direct access to files (Files beyond images, such as text and PDF files -- so the /full/full/0/default.ext isn't sufficient)
* Provide info.json like information about identifiers which aren't images, so wouldn't be the same properties as the existing info.json for images.

Our first draft at planning was to author updated versions of the last 2 features that would be separate from Cantaloupe.

There are efficiency reasons to contemplate if these would be best handled as code in JRuby that would be called from the delegate script.

* Direct file access could be as simple as calling get_pathname(identifier) and sending the file if self.authorized() returns true.  What is needed is an endpoint that offers that direct access, and isn't tied to the existing Image API (IE: Files won't all be called default.ext).
* Not sure about the info.json as not all the identifiers I would want to report on are 'files' and thus wouldn't map to a processor (IE: self.extra_iiif2_information_response_keys(identifier) wouldn't be sufficient).

Any ideas helpful.

We are hoping that something in a delegate script can be set up so that our organisation-specific functionality doesn't have to be a fork of Cantaloupe, but something separate that uses defined APIs.

If this is a sensible thing to be contemplating then let us know as it makes sense for us to spend time enhancing Cantaloupe rather than doing something separate.

**Comment by RussellMcOrmond** [comment]
We decided to design around our info.json API for other identifier types, so this question is only about direct access which should be simpler.

If we worked on a patch to provide an optional call into the JRuby script for this functionality, would that be of interest and something that might get integrated?


Our existing content server made use of XSendfile style functionality (Variations available in Apache and NGINX, using mildly different headers) which passed off the sending of unmodified and image derivative cache files to the external web server.  I'm curious if this has been considered for Cantaloupe?

https://tn123.org/mod_xsendfile/
https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/

**Comment by adolski** [comment]
I'd be inclined to provide separate interfaces for each of these three services, and use Cantaloupe strictly as an IIIF service.

Cantaloupe can already stream source files, but only if they are images. I guess it would be possible to expand this to all file types, but I don't want to abuse the IIIF APIs, and I'm also concerned about feature creep, which I fear could be major as the project morphs into a hybrid content/image server.

Separate from this issue, X-Sendfile could be a nice enhancement for FilesystemResolver & FilesystemCache.

**Comment by RussellMcOrmond** [comment]
With IIIF the authentication API involves something that can set the Access Cookie, which would be within the domain.  Is the suggestion that this be done with Apache ProxyPass such that the services are in the same domain, just not handled by the same back-end service?

**Comment by adolski** [comment]
There's no suggestion, I'm just saying I'm reluctant to add generic-content-serving features at this time.

**Comment by RussellMcOrmond** [comment]
Understood about the generic content serving.  We are new to IIIF, and are curious what other people who use Cantaloupe are doing for Auth.

**Comment by RussellMcOrmond** [comment]
I should have updated.  Sascha created https://github.com/c7a/cihm-file-access to provide authenticated access.   Thanks for the discussion.
