### ISSUE TITLE
Server-side image adjustments beyond IIIF Image API

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#117]
Continued from #115: more image adjustment operations than the IIIF Image API can provide are needed: contrast, brightness, saturation, and others.

Also, currently normalization, resample filter selection, and sharpness can be set on the server, but we lack API to make them user-selectable.

**Comment by imoutsatsos** [comment]
Hi Alex;
I have now been working under the assumption that for quantitative comparisons I will need to review images without normalization and I will be able to adjust the intensity/contrast on the client side to make this possible. As expected, raw images when they are first loaded are really dark and hard to visualize. Client side adjustment of image intensity and contrast does not seem to help much. here is an example:
![image](https://user-images.githubusercontent.com/3408226/29229307-982d7836-7eab-11e7-9a1b-4c90facab306.png)
This is an example of the best I could do with OSD filtering on client side adjusting brightness and contrast. Green channel OK, middle blue channel uninformative, red channel barely visible with very low contrast.
What I really need is to set the low/high level for each color is something like this:
![image](https://user-images.githubusercontent.com/3408226/29229559-11d84d04-7ead-11e7-9e11-975f2c6f5e2c.png)
However, I'm suspecting that the JPEG2000 image tiles that are now loaded in the iiif viewer don't have the same dynamic range as the original TIFF files. As a result I have experienced severe posterization trying to setup the image intensities like this using the CamanJS-Curves function http://camanjs.com/guides/#AdvancedUsage

Any ideas or suggestions greatly appreciated.
Best regards
Ioannis

**Comment by adolski** [comment]
Hi, I think the problem here is that all output is max 8 bits per channel, so all of that "dark" information on the far left end of the histogram in the 16-bit source image is getting collapsed down to just a few bars at 8 bits. Does that sound right?

**Comment by imoutsatsos** [comment]
Yes, I think that's exactly the issue! The served images will need to have their full bit depth if client side adjustments have any chance of working to make these visible as in the original image. The other option of course is server side processing which was the 'old and slow' approach.

**Comment by adolski** [comment]
Hi @imoutsatsos, let's move this to #142.
