### ISSUE TITLE
How to open image with cantaloupe

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#120]
Hi,
Is it possible to open image from path directly from cantaloupe for example:
http://cantaloupe-server:port/path=/operational_storage/derivative_copies/2017/01/24/file_1/V1-FL1048.ptif/full/full/0/default.jpg

Here is path of the image is /operational_storage/derivative_copies/2017/01/24/file_1/V1-FL1048.ptif 
Thank you !

**Comment by adolski** [comment]
Sure is, just use the path in the identifier and URL-encode it. Example:

`FilesystemResolver.BasicLookupStrategy.path_prefix = /operational_storage/derivative_copies/`

`http://cantaloupe-server:port/iiif/2/2017%2F01%2F24%2Ffile_1%2FV1-FL1048.ptif/full/full/0/default.jpg`

**Comment by prilia** [comment]
what to do in case I have files in many folders ?

**Comment by adolski** [comment]
You mean outside of `/operational_storage/derivative_copies/`? You can set `FilesystemResolver.BasicLookupStrategy.path_prefix` to any path, even `/`. Whatever part of the path you don't include there needs to be included in the identifier in the URL.

**Comment by prilia** [comment]
thank you !
