### ISSUE TITLE
Slow image processing time

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#121]
Hi, 
I have a question about image processing time, when I call a full image with:
http://cantaloupe-server:port/iiif/2/FL28301.jpg/full/full/0/default.jpg    
a waiting time is only 691 ms.
and for this 
http://cantaloupe-server:port/iiif/2/FL28301.jpg/full/600,/0/default.jpg
a waiting time is only 2.55 s.
In case of tile like this :
http://cantaloupe-server:port/iiif/2/FL28301.jpg/pct:0,0,50,50/600,/0/default.jpg
a waiting time is only 2.69 s.
I set -Xmx4g and I am using with JaiProcessor, because I have a lot of jpgs and sometime I need a overlays.

Is it possible to tune it better ?
Thank you !

**Comment by adolski** [comment]
With `/full/full/0/default.xxx`, when `xxx` is the same as the source image format, and there is no other processing that has to be done (like overlays), the image will stream out with no processing. That's probably why it's so much faster in this case.

There is some information on serving images efficiently in the user manual: https://medusa-project.github.io/cantaloupe/manual/3.3/images.html

For JPEG images, they are usually OK up to a few megapixels, but the bigger they get, the slower they are to process.
