### ISSUE TITLE
Error 500 - File already exists (FilesystemCache)

### ISSUE THREAD

**Issue by kaij** [medusa-project/cantaloupe#124]
I have quite a few of these errors in the log. Do you have any idea what the problem could be?

```
Caused by: edu.illinois.library.cantaloupe.cache.CacheException: Destination '/var/cache/cantaloupe/info/ea/0b/6e/ea0b6e2db8765a269c93dc1b5b381c8c.json' already exists
nbvv-iiif         | 	at edu.illinois.library.cantaloupe.cache.FilesystemCache.put(FilesystemCache.java:961)
...
```

**Comment by adolski** [comment]
This would happen when the cache is trying to write the same image metadata more than once at the same time. There is a lock that should be preventing multiple threads (i.e. 1 server instance) from doing that, but it looks like multiple processes could cause it. Are you running >1 server instance? If not then I need to look deeper.

**Comment by Eyal-R** [comment]
I'm having a similar issue - but I get HTTP 200 with no data, while the log indicates:

>  ERROR [qtp728890494-16] o.r.C.WebApplication [Slf4jLogger.java:230] Exception or error caught in server resource
> org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
>         at org.restlet.resource.ServerResource.doHandle(ServerResource.java:539)
>         at org.restlet.resource.ServerResource.get(ServerResource.java:742)
>         at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617)
>         at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678)
>         at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356)
>         at org.restlet.resource.ServerResource.handle(ServerResource.java:1043)
>         at org.restlet.resource.Finder.handle(Finder.java:236)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Router.doHandle(Router.java:422)
>         at org.restlet.routing.Router.handle(Router.java:641)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
>         at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
>         at org.restlet.Application.handle(Application.java:385)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Router.doHandle(Router.java:422)
>         at org.restlet.routing.Router.handle(Router.java:641)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.routing.Router.doHandle(Router.java:422)
>         at org.restlet.routing.Router.handle(Router.java:641)
>         at org.restlet.routing.Filter.doHandle(Filter.java:150)
>         at org.restlet.routing.Filter.handle(Filter.java:197)
>         at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
>         at org.restlet.Component.handle(Component.java:408)
>         at org.restlet.Server.handle(Server.java:507)
>         at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
>         at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
>         at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
>         at org.eclipse.jetty.server.Server.handle(Server.java:524)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: edu.illinois.library.cantaloupe.cache.CacheException: Destination '/opt/cantaloupe/3.3/caching/info/7fb/64d/9bc/ffe/7fb64d9bcffe417ec33f8eea933cc6ee.json' already exists
>         at edu.illinois.library.cantaloupe.cache.FilesystemCache.put(FilesystemCache.java:961)
>         at edu.illinois.library.cantaloupe.resource.AbstractResource.getOrReadInfo(AbstractResource.java:611)
>         at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:111)
>         at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523)
>         ... 66 common frames omitted
> Caused by: org.apache.commons.io.FileExistsException: Destination '/opt/cantaloupe/3.3/caching/info/7fb/64d/9bc/ffe/7fb64d9bcffe417ec33f8eea933cc6ee.json' already exists
>         at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2825)
>         at edu.illinois.library.cantaloupe.cache.FilesystemCache.put(FilesystemCache.java:958)
>         ... 72 common frames omitted
> 

It seems similar since it also indicates that the cache json already exists.
I also got some "Caused by: edu.illinois.library.cantaloupe.cache.CacheException: Unable to create directory: /opt/cantaloupe/3.3/caching/info/2ea/81a/61a/fe8"

I do not run multiple serves, only one!
I understand that this issue's fix is on 3.3.4, does it apply to this issue as well (having only 1 server)?

**Comment by RussellMcOrmond** [comment]
I can confirm that 3.3.4 (and 3.3.3 before it, but it had a separate regression) fixes this problem.  I observed the problem right away with 3.3.2, as we have sufficient traffic to have that problem trigger fairly regularly.   We didn't notice it in our test environment (not enough testers I guess), but did notice it in production.

**Comment by Eyal-R** [comment]
Thanks!
