### ISSUE TITLE
Add support for image overlays to ImageMagickProcessor

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#127]
Hello,
I configured ImageMagic as a processor for JPEG and set up overlay yadBZ.png.
When I open the image it's without overlay.
here is the logs:
`11:35:54.958 [qtp1926764753-14] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled from request: http://12.0.12.154:4343
11:35:54.960 [qtp1926764753-14] INFO  e.i.l.c.p.ImageMagickProcessor - readImageInfo(): invoking /usr/bin/magick identify -ping -format %w,%h,%[EXIF:Orientation] jpg:-
11:35:55.375 [qtp1926764753-14] DEBUG e.i.l.c.r.AbstractResource - readInfo(): read from /file_12/V1-FL35786.jpg in 415 msec
11:35:55.395 [qtp1926764753-14] INFO  e.i.l.c.p.ImageMagickProcessor - process(): invoking /usr/bin/magick convert jpg:- -normalize -filter hermite -resize 310 -depth 8 -quality 50% jpg:-
11:35:56.422 [qtp1926764753-14] DEBUG e.i.l.c.r.ImageRepresentation - ImageMagickProcessor processed in 1030 msec: file_12/V1-FL35786.jpg_scale:310,,hermite_imageoverlay:yadBZ.png_SE_10_processor.normali     ze:true_quality:50.jpg
11:35:56.586 [qtp1926764753-15] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled from request: http://12.0.12.154:4343`

Is it possible in case we need overlay on JPEG file, throw exception so the fallback processor will call for creation of overlay ( in this case I'll use with JAI )

I want to set up ImageMagic as a default JPEG processor, because imagemagic faster and only in case of overlay use with jai.

Any ideas ?
Thank you !

**Comment by adolski** [comment]
I think the best solution here would be to add support for image overlays to ImageMagickProcessor.

**Comment by prilia** [comment]
Hi, 
I tested jpeg streaming with cantaloupe 3.3.1 
on Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz server with -Xmx6g.
I checked jai, imagemagic, jav2d. I tested two cases - stream a full picture or tile.
The best results I got with jai processor.
In case of full picture ~3.3M, output is very fast jpeg  is 163msec, but for a tile is very slow 1276 msec because of processing needed.

**http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/full/0/default.jpg**
`10:12:42.625 [qtp728890494-11] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/full/0/default.jpg
...
10:12:42.810 [qtp728890494-11] DEBUG e.i.l.c.r.AbstractResource - readInfo(): read from V1-FL31362.jpg in 177 msec
...
10:12:42.981 [qtp728890494-11] DEBUG e.i.l.c.r.ImageRepresentation - Streamed with no processing in 163 msec: V1-FL31362.jpg_processor.normalize:true_quality:50.jpg`

**http://12.0.12.154:4343/iiif/2/FV1-FL31362.jpg/full/500,/0/default.jpg**
`10:09:34.693 [qtp728890494-17] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/500,/0/default.jpg
10:09:34.696 [qtp728890494-17] INFO  e.i.l.c.r.SourceImageWrangler - FileResolver -> FileProcessor connection between FilesystemResolver and JaiProcessor
...
10:09:35.021 [qtp728890494-17] DEBUG e.i.l.c.r.AbstractResource - readInfo(): read from V1-FL31362.jpg in 324 msec
...
10:09:36.213 [qtp728890494-17] DEBUG e.i.l.c.p.i.JPEGImageWriter - Quality: 50; progressive: false
10:09:36.302 [qtp728890494-17] DEBUG e.i.l.c.r.ImageRepresentation - JaiProcessor processed in 1276 msec: V1-FL31362.jpg_scale:500,_processor.normalize:true_quality:50.jpg
`
Is it possible to add configuration of jai processor like in this [example](http://docs.geoserver.org/stable/en/user/configuration/image_processing/index.html)  ?
![jai configuration](http://docs.geoserver.org/stable/en/user/_images/image_processing.png)

Thank you !
