### ISSUE TITLE
Jpeg with jai processing time

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#128]
Hi, 
I tested jpeg streaming with cantaloupe 3.3.1 
on Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz server with -Xmx6g.
I checked jai, imagemagic, jav2d. I tested two cases - stream a full picture or tile.
The best results I got with jai processor.
In case of full picture ~3.3M, output is very fast jpeg  is 163msec, but for a tile is very slow 1276 msec because of processing needed ( I need tiles for iiif compliance )

**http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/full/0/default.jpg**
`10:12:42.625 [qtp728890494-11] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/full/0/default.jpg
...
10:12:42.810 [qtp728890494-11] DEBUG e.i.l.c.r.AbstractResource - readInfo(): read from V1-FL31362.jpg in 177 msec
...
10:12:42.981 [qtp728890494-11] DEBUG e.i.l.c.r.ImageRepresentation - Streamed with no processing in 163 msec: V1-FL31362.jpg_processor.normalize:true_quality:50.jpg`

**http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/500,/0/default.jpg**
`10:09:34.693 [qtp728890494-17] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://12.0.12.154:4343/iiif/2/V1-FL31362.jpg/full/500,/0/default.jpg
10:09:34.696 [qtp728890494-17] INFO  e.i.l.c.r.SourceImageWrangler - FileResolver -> FileProcessor connection between FilesystemResolver and JaiProcessor
...
10:09:35.021 [qtp728890494-17] DEBUG e.i.l.c.r.AbstractResource - readInfo(): read from V1-FL31362.jpg in 324 msec
...
10:09:36.213 [qtp728890494-17] DEBUG e.i.l.c.p.i.JPEGImageWriter - Quality: 50; progressive: false
10:09:36.302 [qtp728890494-17] DEBUG e.i.l.c.r.ImageRepresentation - JaiProcessor processed in 1276 msec: V1-FL31362.jpg_scale:500,_processor.normalize:true_quality:50.jpg
`
Is it possible to add configuration of jai processor like in this [example](http://docs.geoserver.org/stable/en/user/configuration/image_processing/index.html)  ?
Any ideas to get jpeg tile faster ?

Thank you !

**Comment by adolski** [comment]
None of the processors (including JaiProcessor) are resource-limited in any way -- they all run full-throttle and will use as much CPU and I/O as they are given. Not much I can do, I'm afraid.
