### ISSUE TITLE
Metadata not returned for test TIFFMetadataTest#testGetXmpRdf

### ISSUE THREAD

**Issue by kinow** [medusa-project/cantaloupe#134]
While trying to fix some tests, I encountered one that has been quite difficult to get it to pass.

`TIFFMetadataTest#testGetXmpRdf` is returning `null` for [newInstance(is).getXMPRDF();](https://github.com/medusa-project/cantaloupe/blob/feeef67e122708fd2ec525148183fe9f726d3e78/src/test/java/edu/illinois/library/cantaloupe/processor/imageio/TIFFMetadataTest.java#L94).

The file it is reading in my local workstation is `/home/kinow/Development/java/workspace/cantaloupe/src/test/resources/images/tif-xmp.tif`. I can see the XMP metadata associated with the image with `exiv2`:

```
kinow@kinow:~$ exiv2 -p a /home/kinow/Development/java/workspace/cantaloupe/src/test/resources/images/tif-xmp.tif 
Exif.Image.ImageWidth                        Short       1  64
Exif.Image.ImageLength                       Short       1  56
Exif.Image.BitsPerSample                     Short       4  8 8 8 8
Exif.Image.Compression                       Short       1  Uncompressed
Exif.Image.PhotometricInterpretation         Short       1  RGB
Exif.Image.Make                              Ascii       6  Canon
Exif.Image.Model                             Ascii      21  Canon PowerShot S200
Exif.Image.StripOffsets                      Long        1  490
Exif.Image.Orientation                       Short       1  top, left
Exif.Image.SamplesPerPixel                   Short       1  4
Exif.Image.RowsPerStrip                      Short       1  56
Exif.Image.StripByteCounts                   Long        1  14336
Exif.Image.XResolution                       Rational    1  72
Exif.Image.YResolution                       Rational    1  72
Exif.Image.PlanarConfiguration               Short       1  1
Exif.Image.ResolutionUnit                    Short       1  inch
Exif.Image.Software                          Ascii      11  Photos 1.5
Exif.Image.DateTime                          Ascii      20  2002:07:14 09:01:42
Exif.Image.ExtraSamples                      Short       1  1
Exif.Image.SampleFormat                      Short       4  Unsigned integer data
Exif.Image.XMLPacket                         Byte      1164  (Binary value suppressed)
Exif.Image.IPTCNAA                           Undefined 132  (Binary value suppressed)
Exif.Image.ExifTag                           Long        1  8
Exif.Photo.ExposureTime                      Rational    1  1/20 s
Exif.Photo.FNumber                           Rational    1  F2.8
Exif.Photo.ISOSpeedRatings                   Short       1  50
Exif.Photo.ExifVersion                       Undefined   4  2.20
Exif.Photo.DateTimeOriginal                  Ascii      20  2002:07:14 09:01:42
Exif.Photo.DateTimeDigitized                 Ascii      20  2002:07:14 09:01:42
Exif.Photo.ComponentsConfiguration           Undefined   4  YCbCr
Exif.Photo.CompressedBitsPerPixel            Rational    1  5
Exif.Photo.ShutterSpeedValue                 SRational   1  1/20 s
Exif.Photo.ApertureValue                     Rational    1  F2.8
Exif.Photo.ExposureBiasValue                 SRational   1  0 EV
Exif.Photo.MaxApertureValue                  Rational    1  F2.8
Exif.Photo.MeteringMode                      Short       1  Multi-segment
Exif.Photo.Flash                             Short       1  No, compulsory
Exif.Photo.FocalLength                       Rational    1  5.4 mm
Exif.Photo.FlashpixVersion                   Undefined   4  1.00
Exif.Photo.ColorSpace                        Short       1  sRGB
Exif.Photo.PixelXDimension                   Long        1  64
Exif.Photo.PixelYDimension                   Long        1  56
Exif.Photo.FocalPlaneXResolution             Rational    1  7766.99
Exif.Photo.FocalPlaneYResolution             Rational    1  7741.94
Exif.Photo.FocalPlaneResolutionUnit          Short       1  inch
Exif.Photo.SensingMethod                     Short       1  One-chip color area
Exif.Photo.FileSource                        Undefined   1  Digital still camera
Exif.Photo.CustomRendered                    Short       1  Normal process
Exif.Photo.ExposureMode                      Short       1  Auto
Exif.Photo.WhiteBalance                      Short       1  Manual
Exif.Photo.DigitalZoomRatio                  Rational    1  1.0
Exif.Photo.SceneCaptureType                  Short       1  Standard
Exif.Image.InterColorProfile                 Undefined 3144  (Binary value suppressed)
Iptc.Envelope.CharacterSet                   String      3  
Iptc.Application2.RecordVersion              Short       1  2
Iptc.Application2.Keywords                   String     19  Green Bay / De Pere
Iptc.Application2.Keywords                   String     31  Instructional Services Building
Iptc.Application2.Keywords                   String      4  UWGB
Iptc.Application2.DigitizationDate           Date        8  2002-07-14
Iptc.Application2.DigitizationTime           Time       11  09:01:42+00:00
Iptc.Application2.DateCreated                Date        8  2002-07-14
Iptc.Application2.TimeCreated                Time       11  09:01:42+00:00
Xmp.aux.Lens                                 XmpText    11   5.4-10.8mm
Xmp.aux.FlashCompensation                    XmpText     3  0/1
Xmp.aux.Firmware                             XmpText    21  Firmware Version 1.00
Xmp.aux.OwnerName                            XmpText    11  Alex Dolski
Xmp.xmp.CreateDate                           XmpText    19  2002-07-14T09:01:42
Xmp.xmp.ModifyDate                           XmpText    19  2002-07-14T09:01:42
Xmp.xmp.CreatorTool                          XmpText    10  Photos 1.5
Xmp.photoshop.DateCreated                    XmpText    19  2002-07-14T09:01:42
Xmp.dc.subject                               XmpBag      3  Green Bay / De Pere, Instructional Services Building, UWGB
```

Debugging in Eclipse, it looks like `com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata` is not able to return the XMP, or maybe `IIOMetadata` is not parsing the DOM tree correctly?

I have very little knowledge and experience with imaging in Java, so any help would be really welcome :-)

Thanks!
Bruno

**Comment by kinow** [comment]
Actually, it fails in Eclipse, but works with I run with `mvn clean test -Dtest=TIFFMetadataTest#testGetXmpRdf`... hmmm, let me investigate it...

**Comment by kinow** [comment]
Okay, I believe I found what's going on. See https://github.com/kinow/cantaloupe/commit/e362cd5489d8f0258309eb84cd26b649f74d58b7 for the commit that marks that test to be ignored.

As the test was passing in Maven, and failing in Eclipse, I assumed it would be either some dependency, or a build plug-in. Tried a few different configurations in pom.xml, excluding dependencies, re-ordering, etc.

Then, while debugging, found that the TIFFImageReader implementation loaded in Eclipse (and in Maven as well) came not from javax.imageio, but from geosolutions.it/image-ext-tiff (which supports BigTIFF).

The problem with that implementation is that it utilises [SoftReference](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/SoftReference.html)'s, as in [this example](https://github.com/geosolutions-it/imageio-ext/blob/71720be732a3c4a132355ff149fa258e0cade5ee/plugin/tiff/src/main/java/it/geosolutions/imageioimpl/plugins/tiff/TIFFImageReader.java#L154).

The reason why sometimes this test would fail - even with Maven - and sometimes it would not, is due to the GC removing the metadata, that was previously loaded. Leading to a null XMP metadata in the example of this issue.

I don't know much about the geosolutions.it implementation, but I would expect to be able to find another TIFFImageReader that does not use SoftReference's. Instead providing mechanisms to clear the metadata, or not load at all.

**Comment by kinow** [comment]
In [this case](https://github.com/medusa-project/cantaloupe/blob/feeef67e122708fd2ec525148183fe9f726d3e78/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java#L72) in the Cantaloupe image server, the risk of getting metadata being collected by GC is quite low.

However, [here](https://github.com/medusa-project/cantaloupe/blob/feeef67e122708fd2ec525148183fe9f726d3e78/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/TIFFImageReader.java#L109), if the reader was not null, and already existed, then depending on the time between method calls, and the available memory/memory pressure in the server, the metadata may be null - *I think*.

In case users ever report not being able to read the metadata of valid TIFF files with metadata, this could be the case.

**Comment by adolski** [comment]
Thanks so much for your thorough investigation! This has had me stumped for a while.

What do you think about the GeoSolutions TIFFImageReader's use of a SoftReference here? Simone writes in his doc comment that he's using it because the IIOMetadatas might be big, but how big could they be? Maybe if reading a TIFF with a huge number of pages... which I guess would make sense as this reader was made for use in GIS. But even then, the SoftReference seems like a pretty unreliable (though quick) fix for that. (?)

I guess one way this could be dealt with in the GeoSolutions TIFFImageReader (if they don't want to get rid of the SoftReference) would be to modify its TIFFImageReadParam to add a `setRetainPageMetadata(boolean)` method (or something like that), which would control whether this reference is soft or not.

In the meantime it might be possible to use the Sun TIFFImageReader to get the metadata, but it might also make things more complicated. Also, I don't think it's possible to pass a Sun IIOMetadata to a GeoSolutions TIFFImageWriter, and I imagine it would be hard to convert it to a GeoSolutions one.

**Comment by kinow** [comment]
>But even then, the SoftReference seems like a pretty unreliable (though quick) fix for that. (?)

I think so too. That is a good solution, but as that's a library, IMHO this kind of feature must either have a toggle feature to enable/disable as you suggested, or an alternative solution that does not use it.

>In the meantime it might be possible to use the Sun TIFFImageReader to get the metadata, but it might also make things more complicated. Also, I don't think it's possible to pass a Sun IIOMetadata to a GeoSolutions TIFFImageWriter, and I imagine it would be hard to convert it to a GeoSolutions one.

Forgot to say that I tried using Sun IIOMetadata (I think). I added jai_imageio (that's Sun's library right?) before geosolutions' library in pom.xml. Then I could see that the TIFFFImageReader implementation changed, but after that everything works in Eclipse, but Maven doesn't compile :disappointed: 

```
[ERROR] /home/kinow/Development/java/workspace/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java:[3,42] package com.sun.media.imageio.plugins.tiff does not exist
[ERROR] /home/kinow/Development/java/workspace/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java:[4,42] package com.sun.media.imageio.plugins.tiff does not exist
[ERROR] /home/kinow/Development/java/workspace/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java:[81,23] cannot find symbol
  symbol:   class TIFFDirectory
  location: class edu.illinois.library.cantaloupe.processor.imageio.AbstractMetadata
[ERROR] /home/kinow/Development/java/workspace/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java:[82,25] cannot find symbol
  symbol:   variable TIFFDirectory
  location: class edu.illinois.library.cantaloupe.processor.imageio.AbstractMetadata
[ERROR] /home/kinow/Development/java/workspace/cantaloupe/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/AbstractMetadata.java:[83,23] cannot find symbol
  symbol:   class TIFFField
  location: class edu.illinois.library.cantaloupe.processor.imageio.AbstractMetadata
[INFO] 5 errors
```

**Comment by adolski** [comment]
I'll see if I can patch the GeoSolutions plugin.

For the Sun plugin, try this:

    <dependency>
      <groupId>com.github.jai-imageio</groupId>
      <artifactId>jai-imageio-core</artifactId>
      <version>1.3.1</version>
    </dependency>

This will add `com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader` and also `com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader` (I have no idea what that one is -- maybe the same thing).

The TIFF plugin implementation is selected at runtime [here](https://github.com/medusa-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/processor/imageio/TIFFImageReader.java#L61)

**Comment by kinow** [comment]
I believe it worked!

https://github.com/kinow/cantaloupe/commit/3e013b3181b03039b4135f3f0012f42351f558f0

Removed the Ignore tag, no the test has been re-enabled. Feel free to close this issue if you'd like. 

At another time I would like to investigate the cache + garbage collector. But I can file another issue later for that, or we can leave this one open. Whichever works best for you.

**Comment by adolski** [comment]
I patched the GeoSolutions TIFFImageReader to use hard instead of soft references. After doing that, though, I was still able to reproduce the test failures.

I did find another bug (which might be *the* bug) which was caused by failing to check the ImageReader/Writer implementation before using it. Ran the tests a few more times and haven't seen the failures again since...

**Comment by kinow** [comment]
Nice :tada: ! So probably it wasn't the softreferences after all! Thanks for fixing it :-)

**Comment by adolski** [comment]
No problem. Sorry for breaking it in the first place. 😄
