### ISSUE TITLE
Standardized tests for Cantaloupe implementations

### ISSUE THREAD

**Issue by scossu** [medusa-project/cantaloupe#140]
In order to effectively measure the performance and features of Cantaloupe (or, for what matters, any image server) it would be very valuable to have a test suite that can easily be set up in any existing Cantaloupe implementation. 

The goal is to provide the widest possible terms of comparison between different IIIF server implementations by performing identical and predictable requests on different architectures. 

N.B. This ticket only focuses on Image API performance. 

Characteristics of this test suite should be: 

1. Portability: written in a widespread programming language with few or no dependencies for an average server environment (e.g. PHP, Pyhon, Ruby)
2. Diversity: as many diverse requests as possible should be performed while maintaining the code reasonably uncomplicated
3. Replicability: non-random tests should yield similar results in two identical systems (the difference only being caused by traffic and load not related to the tests)

Some sample images should be provided—at least one large (>4096 px per side) pyramidal TIFF and one JP2 of the same size, as well as a medium-size (~1920 px) pair. All images should be derived from the same source. 

Example tests could be: 

- Retrieve a variety of tiles and other derivatives from the same image; move on to a different format, then to a different base size
- Same as above with 1, 2, 4, 8, 16, 32, 64... concurrent connections
- Compare the above by retrieving tiles in an ordered fashion (i.e. many requests on the same tile at the same time) vs. random order (many different tiles requested at the same time) 
- Isolated tests for region, scaling and rotation

**Comment by adolski** [comment]
Hi @scossu,

This sounds like a legitimate and useful tool. I have to say, though, that I don't want to incorporate it into Cantaloupe, either built-in or as an separate tool. Since it could work with any compliant Image API implementation, there would be no reason to couple it to this one, and so it would be better off in its own repo where it's easier to independently release etc. It's basically just a different project.
