### ISSUE TITLE
16-bit output

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#142]
See background in #117.

I can think of a few ways to accomplish this. Of course it wouldn't work with all formats, only the ones that support 16bpp.

1. Server-side: this would involve adding a configuration key like `processor.reduce_to_8bits`.
2. The IIIF Image API defines [a few different supported formats](http://iiif.io/api/image/2.1/#format), but it doesn't say whether any others are allowed. If so, it might be possible to add `png16` and `tif16`. Is that a good idea? I dunno. Probably not.
3. URL query argument: I don't really want to consider this for reasons I touched on in #115.

**Comment by adolski** [comment]
Having gone with (1), the config key is named `processor.limit_to_8_bits` and it works with Java2dProcessor, JaiProcessor, and KakaduProcessor. It doesn't work with GMP or IMP because these tools only provide a `-depth` argument that forces all output to that value. It may be possible to work around this by reading the sample size into the Info returned by `Processor.readImageInfo()`, and using that to determine a `-depth` argument. I'll look into that.

**Comment by imoutsatsos** [comment]
Hey Alex; Good progress on this! It's becoming a critical point for us whether to continue with the client side approach to image processing using javascript or spend time to pre-process images on the back end. Having the ability to return 16-bit png ot tif  files would be VERY helpful. If we can't use IMP, do you think that we will impact the image server performance. I seem to remember trying the Java2dProcessor and finding it much slower that IMP, but perhaps I need to give it another try to confirm. Let me know when I can test-drive the  new version updates. 
Best regards
Ioannis

**Comment by adolski** [comment]
I'm not sure about the performance difference, but you are certainly welcome to try it out. The changes are available now in the `develop` branch, and to build a snapshot would be: `mvn clean package -DskipTests`

**Comment by imoutsatsos** [comment]
Cool! I'll give it a try. Thank you Alex!

**Comment by imoutsatsos** [comment]
Thanks again for working on this issue @adolski !
Testing the new development branch I still detect the server jpg files as 8-bit depth. Perhaps I don't fully understand what should happen, but here is how I'm testing

Configured the following properties:
```
processor.tif = JaiProcessor
processor.limit_to_8_bits = false
```
Then cleared browser cache and in Chrome Developer Tools I  disabled the cache in the Network tab.
Now, I make image requests to Cantaloupe server while recording network activity.

review one of the 'default.jpg' images coming from the server
![image](https://user-images.githubusercontent.com/3408226/29679629-2458c17a-88d0-11e7-944a-04a686a23746.png)

It still appears to be 8-bit depth. I would expect it to be 16-bit.
Am I missing something?

**Comment by adolski** [comment]
JPEG format doesn't support >8-bit depth, so your URLs would need to end with `.png` or `.tif`.

**Comment by imoutsatsos** [comment]
Interesting! But if I use
```
processor.tif = Java2dProcessor
processor.limit_to_8_bits = false
```
the bit depth is reported as 24!
![image](https://user-images.githubusercontent.com/3408226/29681089-ab05cf48-88d4-11e7-94a4-1648260c0380.png)

**Comment by adolski** [comment]
According to the window title, you're still looking at a JPEG. Here is what `magick identify` shows me:

##### `processor.limit_to_8_bits = false`

default.png PNG 1024x1024 1024x1024+0+0 16-bit Grayscale Gray 1.03623MiB 0.010u 0:00.000
default.tif TIFF 1024x1024 1024x1024+0+0 16-bit Grayscale Gray 1461270B 0.000u 0:00.009

##### `processor.limit_to_8_bits = true`

default.png PNG 1024x1024 1024x1024+0+0 8-bit sRGB 234964B 0.000u 0:00.000
default.tif TIFF 1024x1024 1024x1024+0+0 8-bit sRGB 499643B 0.000u 0:00.000

**Comment by imoutsatsos** [comment]
Thanks Alex! I confirm that this is the case with png and tif.
![image](https://user-images.githubusercontent.com/3408226/29681727-a1310648-88d6-11e7-85b9-5b154bb85650.png)

All I was trying to say earlier is that the ```default.jpg``` when using the Java2dProcessor is identified as 24-bit depth, but as 8-bit when using the JaiProcessor. So does the statement 'JPEG format doesn't support >8-bit depth' still stands?

The **good news** is that I now have a version of Cantaloupe that can serve 16-bit depth images, so I can do some real testing on how intensities can be adjusted on the client side without the 16-bit->8-bit issue.

Your assistance is much appreciated!
Best regards
Ioannis

**Comment by adolski** [comment]
I think there is just some confusion in the terminology: JPEG doesn't support more than 8 bits per sample -- 8 red + 8 green + 8 blue = 24 bits per pixel. So the "bit depth" line in that screenshot is referring to the bit depth of a color component sample.

**Comment by imoutsatsos** [comment]
...and here is a dumb question. Given that I now want the 16-bit png or tif files from Cantaloupe and not jpg how do I configure this? 

In the current version of my application, I load the viewer from an array of info.json files like
```
http://cantaloupeServer:8182/iiif/2/MyPathToFile/myImage.tif/info.json
```
These don't define in any way that I understand the return image file type. Is there some way to configure this in the server properties?

**Comment by adolski** [comment]
`info.json` contains only information about the source image. The output type is specified in the URL:

* http://cantaloupeServer:8182/iiif/2/MyPathToFile/myImage.tif/full/full/0/default.png
* http://cantaloupeServer:8182/iiif/2/MyPathToFile/myImage.tif/full/full/0/default.tif

**Comment by imoutsatsos** [comment]
Yap, that what I thought. And that now seems to be a question more for the OpenSeadragon viewer: https://github.com/openseadragon/openseadragon/issues/1293

**Comment by adolski** [comment]
I think I'm going to call this done, even though GMP/IMP aren't covered, as those will require more wotk and I'd like to get 3.4 on track for release. New tickets for those can be opened in the future, if desired.
