### ISSUE TITLE
Redesign the delegate script

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#148]
The delegate script consists of a bunch of methods organized into Ruby modules. The intention was to make it simple enough that entry-level or maybe even non-programmers could throw something together. I assume it works in most cases, but, because of the statelessness, it's inefficient when multiple delegate methods need to acquire the same information.

One way to fix this would be to redesign it as a class that gets instantiated upon each request. Something like:

```ruby
class CantaloupeDelegate

  def initialize(context)
    @context = context
  end

  def authorized?
    if @context['client_ip'] == '...'
    ...
  end

  def filesystemresolver_get_pathname(identifier)
  end

  ...

end
```

The primary benefit would be the information-sharing. The drawbacks would be:

1. It would break compatibility with the existing script. Most of the methods would have to be renamed, and they would lose their arguments (although there wouldn't be any new or obsoleted methods, and the return values wouldn't change).
2. I assume some users don't understand classes and instances and constructors, so the learning curve would be steeper for them.

Feedback welcome. If this ever happens, it will be in the next major version, at the earliest.

**Comment by SaschaAdler** [comment]
We've had no issues with the current delegate script setup, although this new approach provides clear benefits. One thing I like is that members can be added to the context hash without requiring changes in delegate method signatures.

One thing you can see in our [delegate script](https://github.com/c7a/cihm-cantaloupe/blob/master/delegates.rb) is that we'd like to emit messages detailing why a request was denied authorization. Right now we're just using `puts` for this and it isn't very elegant. With a delegate script redesign, would it make sense to expose a logger to the methods to handle this use case?

**Comment by adolski** [comment]
Hi @SaschaAdler,

The application logger will be accessible from the delegate script in version 3.4. Here's how it works:

https://github.com/medusa-project/cantaloupe/blob/develop/website/manual/3.4/delegate-script.html#L63-L76

**Comment by SaschaAdler** [comment]
Neat! That solves our problem nicely.

**Comment by jonathangreen** [comment]
I really like this idea. It nicely solves my problem where I need to lookup authentication information twice.

**Comment by adolski** [comment]
This is available for preview now on the `feature/new-delegate-script` branch. Feedback is welcome.

To update my sketch above, the new delegate class looks like:

```ruby
class CustomDelegate

  # image server will set this before calling any methods
  attr_accessor :context

  def filesystemresolver_pathname
    identifier = context['identifier']
    ...
  end

  ...

end
```

Here is the documentation for the new design and migration info: https://github.com/medusa-project/cantaloupe/blob/feature/new-delegate-script/website/manual/4.0/delegate-script.html

I hope to merge into `develop` before long, but when that happens, the old delegate script will break.
