### ISSUE TITLE
e.i.l.c.operation.Rotate.getResultingSize returns incorrect values

### ISSUE THREAD

**Issue by SaschaAdler** [medusa-project/cantaloupe#151]
One of the conditions we're testing for in our `authorized?` delegate method is whether the size of the image requested is no larger than a maximum bound we're providing in an authentication token. We're testing this off of the `resulting_size` parameter. When a rotated image is requested the `resulting_size` contains spurious height and width values, even for rotations of multiples of 90 degrees in which this sort of bounding box test should work fine. I dove into the code and it looks like angle values in degrees are being passed into `Math.sin` and `Math.cos`, which take angle values in radians.

If you like, I can write up a bugfix and submit a pull request sometime in the next few weeks, once I have the chance to set up a build environment.

**Comment by adolski** [comment]
Whoops!

Don't worry about a PR, I'll fix this soon. Thanks for reporting.

**Comment by adolski** [comment]
Fixed in 4c2919ba7601bce718b203e66d2357f8c15d602a
