### ISSUE TITLE
CORS issue with cached info.json

### ISSUE THREAD

**Issue by jweisman** [medusa-project/cantaloupe#155]
We are getting CORS errors when visiting an info.json file from a second IIIF viewer. I believe the `Vary` header should include `Origin` so that the browser makes a new request with the updated `Origin`.

To reproduce, visit:
https://universalviewer.io/uv.html?manifest=https://eu.alma.exlibrisgroup.com/view/iiif/presentation/EXLDEV1_INST/1232929980000121/manifest

Then visit:
https://eu.alma.exlibrisgroup.com/view/universalViewer/?manifest=https://eu.alma.exlibrisgroup.com/view/iiif/presentation/EXLDEV1_INST/1232929980000121/manifest

And receive the following error:
```
app.html:1 Failed to load https://eu-img01.ext.exlibrisgroup.com/iiif/2/eyJyZWdpb24iOiJldS1jZW50cmFsLTEiLCJidWNrZXQiOiJldS1zd5TVCJ9/info.json: The 'Access-Control-Allow-Origin' header has a value 'https://universalviewer.io' that is not equal to the supplied origin. Origin 'https://eu.alma.exlibrisgroup.com' is therefore not allowed access.
```

**Comment by adolski** [comment]
I think this is a duplicate of #107

**Comment by jweisman** [comment]
Yes- it is indeed a duplicate. I see your PR was accepted and now we're waiting for [Restlet Framework](https://github.com/restlet/restlet-framework-java) version 2.3.11 to be released. Thanks.
