### ISSUE TITLE
Leaking KakaduProcessor /dev/stdout symlinks

### ISSUE THREAD

**Issue by cbeer** [medusa-project/cantaloupe#159]
We're seeing a problem with the KakaduProcessor's symlink for `/dev/stdout` (e.g. `/var/cache/tomcat/temp/cantalope-{UUID}.tif`) never getting cleaned up (and eventually consuming all the inodes for whatever disk it is pointed at). These symlinks seem to persist even after restarting tomcat.

We're still investigating, so more details to come.

**Comment by adolski** [comment]
Hi @cbeer,

I'm not able to reproduce this. in either macOS or Linux, standalone or in Tomcat 8.0.32.

Even if the symlink wasn't getting cleaned up, there is only one created per application launch, so I'm surprised that so many would be accumulating.

**Comment by cbeer** [comment]
> Even if the symlink wasn't getting cleaned up, there is only one created per application launch, so I'm surprised that so many would be accumulating.

Interesting; that's not the behavior we're seeing running openjdk 1.8.0_20-b26 with tomcat 7.0.81. We're observing a new symlink created for every(?) request.

**Comment by adolski** [comment]
Sorry, I was looking at the `release/3.3` branch. I see it now. The above commit ought to fix it.

**Comment by cbeer** [comment]
Thanks, that seems to do it.
