### ISSUE TITLE
Force ImageIO plugins reload on startup

### ISSUE THREAD

**Issue by mmatela** [medusa-project/cantaloupe#162]
I'd like to suggest that Cantaloupe should make a call to `ImageIO.scanForPlugins()` at the end of its initialization. This small improvement would save a lot of time and frustration in a rare kind of scenario I just found myself in.

In my scenario, Cantaloupe is one of two apps loaded into Tomcat. The other app is loaded first and during startup it invokes some operations that use imageIO api - thus the plugins scan is performed, before Cantalupe is loaded. As a result, some crucial libraries shipped with Cantaloupe (like jai_imageio) are not available at runtime, Cantaloupse doesn't work and gives rather unhelpful messages in logs (Unable to determine the format of the source image). We've lost a whole day figuring this out!

**Comment by adolski** [comment]
Thanks for reporting this, @mmatela. The fix above will make it into 3.3.3. Sorry for the frustration.
