### ISSUE TITLE
MySQL within JRuby

### ISSUE THREAD

**Issue by jonathangreen** [medusa-project/cantaloupe#165]
I am attempting to query MySQL within a delegate script. I'm working from the development branch because I need #137 in order to make the queries I need. I was wondering if anyone has had any success with this sort of a setup that you know of?

I can run my delegate fine from jruby on the command line, but I can't get the delegate script to run within cantaloupe. 

```
Caused by: javax.script.ScriptException: org.jruby.embed.InvokeFailedException: java.sql.SQLException: No suitable driver found for jdbc:mysql://db_host/database?autoReconnect=true&useSSL=false
```

My delegate looks something like this: 
```ruby
require 'jdbc/mysql'

module Cantaloupe
  module HttpResolver
    def self.get_url(identifier, context)
        token = context['headers']['x-token-header']
        Jdbc::MySQL.load_driver
        url = "jdbc:mysql://db_host/database?autoReconnect=true&useSSL=false"
        connection = java.sql.DriverManager.get_connection(url, 'username', 'password')
        query = "SELECT blah blah blah"
        statement = connection.prepare_statement(query)
        statement.setString(1, token)
        results = statement.execute_query
        
        if results.next 
          user = results.getString('user.name')
          pass = results.getString('user.pass')
        else
          user = 'anonymous'
          pass = 'anonymous'
        end
        return { 
          'uri' => "http://fancy.uri",
          'username' => user,
          'secret' => pass
        }
      else 
        return nil
      end     
    end
  end
end
```

My understanding is that `Jdbc::MySQL.load_driver` should handle all the driver setup, and it does when I running with jruby, but it doesn't seem to be working when running though Cantaloupe. I am passing cantaloupe both the GEM_PATH environment variable and adding `mysql-connector-ja-5.1.44-bin.jar` to the class path. 

I'm running Cantaloupe standalone with the following command: 
```bash
GEM_PATH=/path/to/my/gems java -classpath /path/to/mysql-connector-ja-5.1.44-bin.jar -Dcantaloupe.config=/path/to/cantaloupe/cantaloupe.properties -Xmx500m -jar Cantaloupe-3.4-SNAPSHOT.war
```

**Comment by kinow** [comment]
Not a user of the delegate script yet, but chiming in anyway (-: but I would investigate the possibility that `-cp` is not used when you run with `-jar` your application.

To check that, I'd simply open Cantaloupe-3.4-SNAPSHOT.war, find its META-INF/MANIFEST.MF, get the entry main class, and create the command line equivalent (i.e. instead of `java -jar Cantaloupe-3.4-SNAPSHOT.war`, it would be something like `java -cp Cantaloupe-3.3.3.war edu.illinois.library.cantaloupe.StandaloneEntry`).

Finally, I'd execute the command with the delegate script and with the extra jar. So probably something like:

```
GEM_PATH=/path/to/my/gems java -classpath /path/to/mysql-connector-ja-5.1.44-bin.jar:/path/to/Cantaloupe-3.4-SNAPSHOT.war -Dcantaloupe.config=/path/to/cantaloupe/cantaloupe.properties -Xmx500m edu.illinois.library.cantaloupe.StandaloneEntry
```

Not sure if that would work though, just my two cents :-)

**Comment by adolski** [comment]
The following works for me. I have the Connector/J jar on my classpath but am not using any extra gems:

```ruby
def self.get_url(identifier, context)
  Java::com.mysql.jdbc.Driver
  connection = nil, statement = nil
  url = "jdbc:mysql://db_host/database?autoReconnect=true&useSSL=false"
  begin
    connection = java.sql.DriverManager.get_connection(url, 'username', 'password')
    query = "SELECT url FROM images WHERE identifier = ?"
    statement = connection.prepare_statement(query)
    statement.setString(1, identifier)
    results = statement.execute_query
    return results.next ? results.getString('url') : nil
  ensure
    connection.close if connection
    statement.close if statement
  end
end
```

**Comment by jonathangreen** [comment]
Thanks guys! Super appreciate the help. You were totally correct @kinow, turns out I wasn't putting the jar on the class path correctly. I didn't realize you couldn't use -cp and -jar in the same java invocation. 🤦‍♂️
