### ISSUE TITLE
Redirect from {identifier} to {identifier}/info.json doesn't respect X-IIIF-ID header

### ISSUE THREAD

**Issue by jonathangreen** [medusa-project/cantaloupe#167]
The identifier here should probably respect the `X-IIIF-ID` header, so the client gets a correct redirect.

https://github.com/medusa-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/InformationResource.java#L45-L46

**Comment by jonathangreen** [comment]
Just wanted to make a ticket to make sure you were okay with this redirect using `X-IIIF-ID`. If you are I'll make a PR for it.

**Comment by adolski** [comment]
Hi,

You are correct about this. I'd like to fix it on `release/3.3` and merge into `develop`, but there are going to be a lot fo merge conflicts and I'd like to also do some refactoring around this, so don't worry about the PR -- I'll get to it shortly. Thanks for reporting.

**Comment by jonathangreen** [comment]
Okay. Thanks for the help! 👍
