### ISSUE TITLE
"Link" Header in HTTP Response from Cantaloupe

### ISSUE THREAD

**Issue by Eyal-R** [medusa-project/cantaloupe#173]
Hi!
I've noticed that Cantaloupe adds a "Link" in the HTTP response, that has the link you used in the HTTP Request.
We are using a reverse proxy, which among others translates the UID of the object to a file name, so the actual link that the reverse proxy uses in the HTTP request to Cantaloupe is different than what the user sees, and includes the internal file path in our storage.

Therefore, the Link header reveals to the user the "hidden" information which I would rather not to reveal - the file path in our storage and some more parameters we use in the request.

Is there a way to remove the "Link" header by configuration?

**Comment by adolski** [comment]
Hi @Eyal-R,

Is your reverse proxy server sending `X-Forwarded` headers and an `X-IIIF-ID` header ([see here](https://medusa-project.github.io/cantaloupe/manual/3.3/deployment.html#Reverse-Proxying))? If so, then the `Link` header will respect them.

Example:

```
curl -v -X HEAD \
    -H "X-Forwarded-Proto: HTTP" \
    -H "X-Forwarded-Host: example.org" \
    -H "X-Forwarded-Port: 8080" \
    -H "X-Forwarded-Path: /newpath" \
    -H "X-Forwarded-For: 10.10.10.10" \
    -H "X-IIIF-ID: newid" \
    http://localhost:8182/iiif/2/image.jpg/full/10,/0/default.jpg
```

Link header:

`Link: <http://example.org:8080/newpath/iiif/2/newid/full/10,/0/default.jpg>;rel="canonical"`

**Comment by Eyal-R** [comment]
I have used only X-IIIF-ID, I see now that I must use them all - will do.
Thanks!
