### ISSUE TITLE
Support CMYK JPEGs in Java2dProcessor

### ISSUE THREAD

**Issue by RussellMcOrmond** [medusa-project/cantaloupe#177]
Now that we have Cantaloupe in production I suspect we'll notice more 'interesting' files in our several decades of scanned images.

Here is a sequence to demonstrate the problem:

* Enable "developer tools" in Chrome, Firebug for Firefox or equivalent that will show network traffic 
* Go to http://parl.canadiana.ca/view/oop.debates_HOC0104_01/1?r=0&s=1
* The first page will have "There was an error retrieving this page." where on other pages there is an image.
* Open the URL for the first image in a new tab (It has the 0001.jpg just before /full.  Cantaloupe is also only returning 586 bytes, which represent the headers alone).  This URL has an authorisation token, which is why I needed to describe it this way.  You will note that the page is blank.
* If you change the /!800,800/ in the URL to /full/ you will see the image directly streamed to you (unmodified by Cantaloupe).

When I look in the logs for this image I find the following:

```
19:46:14.178 [qtp94438417-31] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://image.swiss.canadiana.ca/iiif/2/oop.debates_HOC0104_01%2Fdata%2Fsip%2Fdata%2Ffiles%2F0001.jpg/full/!800,800/0/default.jpg?token=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTE1NTAzNzQsImRlcml2YXRpdmVGaWxlcyI6Im9vcC5kZWJhdGVzX0hPQzAxMDRfMDEvZGF0YS9zaXAvZGF0YS9maWxlcy8wMDAxLmpwZyIsImlzcyI6IkNBUCIsIm1heERpbWVuc2lvbiI6ODAwLCJpYXQiOjE1MTE0NjM5NzR9.FPskz1I4JC-EPMcJSwMS06Zq1Kz0ngTOD7Ybi_8Qegc
19:46:14.626 [qtp94438417-31] INFO  e.i.l.c.r.SourceImageWrangler - FileResolver -> FileProcessor connection between FilesystemResolver and Java2dProcessor
19:46:14.632 [qtp94438417-31] INFO  e.i.l.c.r.FilesystemResolver - Resolved oop.debates_HOC0104_01/data/sip/data/files/0001.jpg to /repository/poolaip/cihmz2/oop/213/oop.debates_HOC0104_01/data/sip/data/files/0001.jpg
19:46:14.633 [qtp94438417-31] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): hit: /var/cache/cantaloupe/info/9a/c0/da/9ac0dad1a792f20a85c64d31a0d80fe1.json
19:46:14.778 [qtp94438417-31] INFO  e.i.l.c.c.FilesystemCache - newDerivativeImageOutputStream(OperationList): miss; caching oop.debates_HOC0104_01/data/sip/data/files/0001.jpg_scale:!800,800,bicubic_token:eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTE1NTAzNzQsImRlcml2YXRpdmVGaWxlcyI6Im9vcC5kZWJhdGVzX0hPQzAxMDRfMDEvZGF0YS9zaXAvZGF0YS9maWxlcy8wMDAxLmpwZyIsImlzcyI6IkNBUCIsIm1heERpbWVuc2lvbiI6ODAwLCJpYXQiOjE1MTE0NjM5NzR9.FPskz1I4JC-EPMcJSwMS06Zq1Kz0ngTOD7Ybi_8Qegc_interlace_quality:80.jpg
19:46:14.784 [qtp94438417-31] INFO  e.i.l.c.r.ImageRepresentation - write(): Unsupported Image Type
19:46:14.784 [qtp94438417-31] INFO  e.i.l.c.c.FilesystemCache - purge(OperationList): purging oop.debates_HOC0104_01/data/sip/data/files/0001.jpg_scale:!800,800,bicubic_token:eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTE1NTAzNzQsImRlcml2YXRpdmVGaWxlcyI6Im9vcC5kZWJhdGVzX0hPQzAxMDRfMDEvZGF0YS9zaXAvZGF0YS9maWxlcy8wMDAxLmpwZyIsImlzcyI6IkNBUCIsIm1heERpbWVuc2lvbiI6ODAwLCJpYXQiOjE1MTE0NjM5NzR9.FPskz1I4JC-EPMcJSwMS06Zq1Kz0ngTOD7Ybi_8Qegc_interlace_quality:80.jpg...
```

It should be possible using the /full/ and the same access token to download the image and use it as a test case to diagnose the problem.

Thanks for any insight.

**Comment by adolski** [comment]
Hi @RussellMcOrmond,

The ImageIO JPEG plugin that Java2dProcessor normally uses (`com.sun.imageio.plugins.jpeg.JPEGImageReader`) unfortunately can't read CMYK JPEGs. I'm sure there are workarounds to get them working, but I'll have to look into it.

**Comment by RussellMcOrmond** [comment]
Thank you for looking into this.  Interestingly, jhove doesn't notice the difference, but ImageMagick's 'identify' command does.

```
cihm@quark:/opt/wip/Temp/export/oop_issues/oop.debates_HOC0104_01-sip/data/files$ identify -verbose -format "%f %[colorspace]\n" 000[1-4].jpg 
0001.jpg CMYK
0002.jpg Gray
0003.jpg Gray
0004.jpg Gray

```
