### ISSUE TITLE
FilesystemCache source cache expiration

### ISSUE THREAD

**Issue by jhosteny** [medusa-project/cantaloupe#180]
Thanks for the great project. It's been very useful for us.

The `FilesystemCache` does not perform purging of the source cache based on expiration. I noticed that this behavior has been changed in devel. Would you consider a patch to address this for 3.3.5? Since that code has been re-written fairly extensively, I'd probably elect to just keep it simple and copy the block seen here, but with the appropriate changes for the source cache:

https://github.com/medusa-project/cantaloupe/blob/750deaf17c9c2c44c12e2d1f77a3c782e1ce8307/src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java#L869

**Comment by adolski** [comment]
Yes, you are right. Looks like `FilesystemCacheTest.testPurgeExpired()` is hiding this by asserting 1 when it should be asserting 0 here: https://github.com/medusa-project/cantaloupe/blob/750deaf17c9c2c44c12e2d1f77a3c782e1ce8307/src/test/java/edu/illinois/library/cantaloupe/cache/FilesystemCacheTest.java#L568

I would absolutely welcome a patch.
