### ISSUE TITLE
width*height > Integer.MAX_VALUE!

### ISSUE THREAD

**Issue by Lordkodo** [medusa-project/cantaloupe#187]
Hello,

I try to use Cantaloupe, but when zoom i got this error on server:
> write(): width*height > Integer.MAX_VALUE!

and no image in response (but a status 200)

When my iiif client send this request, it work perfectly.
> http://localhost:8182/iiif/2/tata.ndpi/0,26048,38112,13024/4764,/0/default.jpg

but with this one (bigger zoom) it keep failing
> http://localhost:8182/iiif/2/tata.ndpi/19056,19536,19056,6512/4764,/0/default.jpg

I use OpenSeaDragon, if you want to see the config for OSD or Cantaloupe, tell me.

**Comment by adolski** [comment]
Hi @Lordkodo,

Could you tell me more about your source image: its dimensions and format, and what processor you are using with it?

It would also be helpful if I could download it to look at.

**Comment by Lordkodo** [comment]
Hi @adolski 

It's a NDPI image, I give you info.json:
```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "http://localhost:8182/iiif/2/tata.ndpi",
  "protocol": "http://iiif.io/api/image",
  "width": 59520,
  "height": 41216,
  "sizes": [
    {
      "width": 116,
      "height": 81
    },
    {
      "width": 233,
      "height": 161
    },
    {
      "width": 465,
      "height": 322
    },
    {
      "width": 930,
      "height": 644
    },
    {
      "width": 1860,
      "height": 1288
    },
    {
      "width": 3720,
      "height": 2576
    },
    {
      "width": 7440,
      "height": 5152
    },
    {
      "width": 14880,
      "height": 10304
    },
    {
      "width": 29760,
      "height": 20608
    }
  ],
  "tiles": [
    {
      "width": 7440,
      "height": 5152,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128,
        256,
        512
      ]
    },
    {
      "width": 19056,
      "height": 6512,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128,
        256,
        512
      ]
    },
    {
      "width": 59520,
      "height": 41216,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128,
        256,
        512
      ]
    },
    {
      "width": 19040,
      "height": 6496,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128,
        256,
        512
      ]
    }
  ],
  "profile": [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats": [
        "tif",
        "jpg",
        "gif",
        "png"
      ],
      "qualities": [
        "bitonal",
        "default",
        "gray",
        "color"
      ],
      "supports": [
        "regionByPx",
        "sizeByW",
        "sizeByWhListed",
        "cors",
        "regionSquare",
        "sizeByDistortedWh",
        "sizeAboveFull",
        "canonicalLinkHeader",
        "sizeByConfinedWh",
        "sizeByPct",
        "jsonldMediaType",
        "regionByPct",
        "sizeByH",
        "rotationArbitrary",
        "baseUriRedirect",
        "rotationBy90s",
        "profileLinkHeader",
        "sizeByForcedWh",
        "sizeByWh",
        "mirroring"
      ]
    }
  ]
}
```

I'm actually in a docker container, on a mac. With an Intel Core i7.

Sadly, I can't give you the image, it's sensible information :(

**Comment by adolski** [comment]
It's probably the format that is the problem. Neither of the TIFF-optimized processors (Java2dProcessor & JaiProcessor) have declared support for NDPI or been tested with it.

From the [format documentation](http://openslide.org/formats/hamamatsu/):

> NDPI uses a TIFF-like structure, but libtiff cannot read the headers of an NDPI file. This is because NDPI specifies the RowsPerStrip as the height of the file, and after doing out the multiplication, this typically overflows libtiff and it refuses to open the file.

That would explain the `width*height > Integer.MAX_VALUE!` error...
