### ISSUE TITLE
Edge case: `quality` = `color` with grayscale or bitonal source images

### ISSUE THREAD

**Issue by adam-vessey** [medusa-project/cantaloupe#192]
Presently, it appears the implementation expects all source images to be colour, with transformations being performed to grayscale or bitonal when requested; however, there appear to be a couple of potential issues if dealing with a source which happens to be grayscale or bitonal:

1. [Specifying `color` for a quality will continue to provide the same as the source](https://github.com/medusa-project/cantaloupe/blob/a613b7b71d974f9fa8035b72826cabf4684d5362/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/Quality.java#L10-L17). The [expected behaviour](http://iiif.io/api/image/2.1/#quality) here is unclear:
    1. should the request HTTP 400, since getting a colour version of an image lacking colour information is not possible? Alternatively,
    2. should it return an image in a "colour" colorspace, despite not really containing any colour information... somewhat inefficient, but if it is what has been requested, then perhaps it is needed?
2. Unnecessary image rewrite operations may be performed if the source and requested quality are the same, as the colorspace of the source does not appear to be checked... for example:
    1. [Java2DUtil](https://github.com/medusa-project/cantaloupe/blob/a613b7b71d974f9fa8035b72826cabf4684d5362/src/main/java/edu/illinois/library/cantaloupe/processor/Java2DUtil.java#L899-L910)
    2. [ImageMagickProcessor](https://github.com/medusa-project/cantaloupe/blob/a613b7b71d974f9fa8035b72826cabf4684d5362/src/main/java/edu/illinois/library/cantaloupe/processor/ImageMagickProcessor.java#L436-L444) (possibly less of an issue)

This is not presently an issue for us, nor do I foresee it being an issue in our usage: Just highlighting the existence of an edge case.

**Comment by adolski** [comment]
Thanks for pointing out that issue in `Java2DUtil.transformColor()`, @adam-vessey.

ImageMagickProcessor will be harder to address since the relevant info will have to be read out of `magick identify` and into an `Info`. So I'm inclined to just leave it be.

Will add my thoughts on (1) sometime soon.

**Comment by adam-vessey** [comment]
Just thoughts about the ImageMagick bit: The reason I indicated it might be less of an issue is because it just adds to the arguments for the underlying invocation... Hypothetically, ImageMagick itself might be able to ignore instructions which do not introduce a change... Very naive  investigation (take it with a grain of salt) into their codebase indicates this may be the case:

* [`TransformImageColorspace()`](https://github.com/ImageMagick/ImageMagick/blob/beb4c2b6fc958ce24feb400366624b3f1979759b/MagickCore/colorspace.c#L1335-L1336), which when setting to the same colorspace calls:
* [`SetImageColorspace()`](https://github.com/ImageMagick/ImageMagick/blob/beb4c2b6fc958ce24feb400366624b3f1979759b/MagickCore/colorspace.c#L1149-L1150) which short-circuits before the transform.

Similarly, it appears [`SetImageMonochrome()` short-circuits on bitonal images](https://github.com/ImageMagick/ImageMagick/blob/beb4c2b6fc958ce24feb400366624b3f1979759b/MagickCore/colorspace.c#L1281-L1282).

I suspect [GraphicsMagickProcessor](https://github.com/medusa-project/cantaloupe/blob/a613b7b71d974f9fa8035b72826cabf4684d5362/src/main/java/edu/illinois/library/cantaloupe/processor/GraphicsMagickProcessor.java#L325-L333) may do [much the same](http://hg.code.sf.net/p/graphicsmagick/code/file/41450966d550/Magick%2B%2B/lib/Image.cpp#l2576).

**Comment by adolski** [comment]
I agree that the Image API spec is unclear on the behavior of `quality` in this situation, so I [asked the experts](https://groups.google.com/forum/#!forum/iiif-discuss). It sounds like as long as support for `color` is declared in the `info.json`, it can be used to pass through images regardless of their color information, which is how it works now in Cantaloupe.

**Comment by adolski** [comment]
https://github.com/IIIF/api/issues/1363

**Comment by adolski** [comment]
Following up on the other part of this thread -- for IMP and GMP, I think I'm going to just let IM & GM figure out the color conversion themselves. It's difficult to do things conditionally with the command-line tools and I don't think the cost/benefit ratio favors spending much time on it.
