### ISSUE TITLE
path_prefix for S3 buckets

### ISSUE THREAD

**Issue by dmajano** [medusa-project/cantaloupe#193]
Hi,

Recently i have started to test the product and it is very interesting and powerful. All my infrastructure is on Amazon Web Service Platform.

I'm using two S3 buckets. one for resolver and the other for cache but i have a big problem. Exist the path_prefix parameter for FileSystem (FilesystemResolver.BasicLookupStrategy.path_prefix ) but not for S3.

If I started to push all my company images (+500) to the resolver S3 bucket without a structure subfolders it will be a chaos. 

Could be this feature developed? 

Thanks you very much!

**Comment by adolski** [comment]
Hi @dmajano,

This sounds like a good idea for an enhancement. In the meantime you could achieve the same result using the delegate script:

# cantaloupe.properties

```properties
delegate_script.enabled = true
AmazonS3Resolver.lookup_strategy = ScriptLookupStrategy
```

# delegates.rb

```ruby
module AmazonS3Resolver
  def self.get_object_key(identifier, context)
    'my/path/prefix/' + identifier
  end
end
```

**Comment by dmajano** [comment]
@adolski I'm receiving the following error with a 500 code:

org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Cantaloupe

Thanks you!

**Comment by kinow** [comment]
Maybe you are missing the wrapper Cantaloupe module? Have a look at this page to see if it helps

https://medusa-project.github.io/cantaloupe/manual/3.4/delegate-script.html

There's a short example of a `delegates.rb` script, with the `module Cantaloupe` declaration.

**Comment by dmajano** [comment]
Thanks @kinow. This is the first thing that I tried but with the same result :(

**Comment by adolski** [comment]
File not found? 🤷‍♂️

Anyway, this feature is now available on the `develop` branch and will go into 4.0. Thanks for the suggestion!
