### ISSUE TITLE
s3Resolver and Kakadu

### ISSUE THREAD

**Issue by kevinportlock** [medusa-project/cantaloupe#194]
Hi,

I'm trying to setup a cantaloupe solution to display JPEG2000 images, hosted in AWS.
All working well until I move images into S3.

I'm getting the following error:
![image](https://user-images.githubusercontent.com/29748655/35775360-6ba4330c-09db-11e8-83ca-d87a1a2ee896.png)

Is this a configuration issue, or just won't work?

Thanks.

**Comment by adolski** [comment]
Hi @kevinportlock,

KakaduProcessor can currently only read images from a filesystem. There's a way to get around it using the source cache; see [here](https://medusa-project.github.io/cantaloupe/manual/3.4/caching.html#Source%20Cache) for more info.

**Comment by kevinportlock** [comment]
Thank you @adolski, that worked perfectly.
