### ISSUE TITLE
Improve efficiency of source cache content access

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#201]
Continued from #179: when there is an item in the source cache, the resolver checks for it in its source location even ehen `cache.server.resolve_first = false`. The request handlers (`doGet()`) ought to check the source cache earlier in the request cycle before any resolver methods are called.

**Comment by adolski** [comment]
The above commit skips the access check (which for HttpResolver makes a `HEAD` request) when `cache.server.resolve_first = false` and the source image is contained in the source cache. This is a general efficiency improvement that affects all resolvers except FilesystemResolver when the source cache is enabled.

**Comment by qadan** [comment]
This is pretty fantastic, thank you so much! I think this is going to go into immediate use where I'm at.

**Comment by adolski** [comment]
Cool.

One remaining issue in this situation is that HttpResolver will still issue a `HEAD` request if the source image format can't be inferred from the filename extension in the identifier. I will see if the format can be read from the source-cached image instead.

**Comment by adolski** [comment]
That's about all there is to do, I think. Thanks for bringing this up and hanging in there with me, @qadan. Source cache access is probably now quite a bit more efficient for everyone with `cache.server.resolve_first = false`.
