### ISSUE TITLE
Question: Multiple resolvers of the same type with different parameters?

### ISSUE THREAD

**Issue by gigamorph** [medusa-project/cantaloupe#204]
Hello,

I'd like to source the images from different S3 buckets depending on the pre-defined namespace portion of the identifier. It seems I can return different resolver modules (e.g. FileSystemResolver and AmazonS3Resolver) using a delegate method but I couldn't figure out how I can use the AmazonS3Resolver module to access different buckets conditionally. Is it possible at all?

**Comment by adolski** [comment]
Here's an example using `AmazonS3Resolver.lookup_strategy = ScriptLookupStrategy` in 3.4:

```ruby
module AmazonS3Resolver
  def self.get_object_key(identifier, context)
    if identifier.start_with?('cats')
      return {
        'bucket' => 'cat-bucket'
        'key' => 'whatever'
      }
    elsif identifier.start_with?('dogs')
      return {
        'bucket' => 'dog-bucket'
        'key' => 'whatever'
      }
    end
    nil
  end
end
```

**Comment by gigamorph** [comment]
Ah, thanks!
