### ISSUE TITLE
Using slash_substitute - propagation to info.json response

### ISSUE THREAD

**Issue by filak** [medusa-project/cantaloupe#207]
Slash substitute is very useful. Though I have noticed that the substitution is not used in info.json response.

The @id property contains %2F instead of the string substitute.

I have been testing Cantaloupe with OpenSeadragon viewer and this cause problems. 

I had to fix this in the openseadragon.js script manually in order to get it working:

`
function loadTile( tiledImage, tile, time ) {
    tile.loading = true;
    tiledImage._imageLoader.addJob({
        src: tile.url.replace('%2F','---'),`

**Comment by adolski** [comment]
Thanks for reporting this, @filak. Looks like a bug that has been around for a long time. Fix now available on `release/3.4` branch and will be in 3.4.2.
