### ISSUE TITLE
URL Location unencoded

### ISSUE THREAD

**Issue by bseeger** [medusa-project/cantaloupe#208]
I'm not sure if this is an issue or not, but it's definitely causing my setup to not work (Open Sea Dragon in Islandora 7). 

I'm  running the lastest release (3.4.1) in stand alone mode on CentOS. 

When I request an image, I get the redirect to the info.json file. That looks good, but I'm using the HttpResolver and am seeing the Location with the URL unencoded, so the client (open sea dragon) get's a 404 because it doesn't realize it needs to encode that section of the path containing the URL. 

BuckyKatt:/Users/bseeger>curl -v localhost:8090/iiif/2/https%3A%2F%2Fdam-dev1.removed.edu%2Fislandora%2Fislandora%2Fobject%2Fislandora%253A159%2Fdatastream%2FJP2%2Fview%3Ftoken%3Db87d0576f7b98c126fb2cd49314ae7aaf6e96f78526bd18c8c2b773e35b796f2
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8090 (#0)
> GET /iiif/2/https%3A%2F%2Fdam-dev1.removed.edu%2Fislandora%2Fislandora%2Fobject%2Fislandora%253A159%2Fdatastream%2FJP2%2Fview%3Ftoken%3Db87d0576f7b98c126fb2cd49314ae7aaf6e96f78526bd18c8c2b773e35b796f2 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8090
> Accept: */*
> 
< HTTP/1.1 303 See Other
< Content-Type: application/octet-stream
< Date: Mon, 02 Apr 2018 15:34:55 GMT
< Location: http://localhost:8090/iiif/2/https://dam-dev1.removed.edu/islandora/islandora/object/islandora%3A159/datastream/JP2/view?token=b87d0576f7b98c126fb2cd49314ae7aaf6e96f78526bd18c8c2b773e35b796f2/info.json
* Server Restlet-Framework/2.3.11 is not blacklisted
< Server: Restlet-Framework/2.3.11
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Origin, Accept
< X-Powered-By: Cantaloupe/3.4.1
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

Am I doing something wrong or missing a setting?  

Thanks!

**Comment by adolski** [comment]
Hi @bseeger,

Thanks for reporting this. The above commit ought to fix it. It will be included in 3.4.2, to be released any day now.

**Comment by bseeger** [comment]
THANK YOU! Works great now!  :)
