### ISSUE TITLE
Connections to S3 buckets are failing when the image format is jpg ( Connection leased)

### ISSUE THREAD

**Issue by dmajano** [medusa-project/cantaloupe#210]
Hi all,

# Cantaloupe image version: 3.4.2

I have started to use Cantaloupe Image Server some months ago. The product its fantastic but today I have found the resolver and cache method using AWS S3 buckets with jpg images is failing. (Since the beginning with png images it works perfectly).

Seeing the tomcat log, the app connects with cache bucket firstly but the image only there is in the resolver bucket so the app tries to download the image.jpg from this source but the following error appears:

**Connection leased: [id: 15][route: {s}->https://my_cache_s3_bucket.s3.eu-west-1.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 100; total allocated: 1 of 100]** 

At the end of the log you can see:

**15:02:21.123 [http-nio-8080-exec-6] ERROR o.r.C.Server - An exception occurred writing the response entity
java.lang.NullPointerException: null
.....
15:02:21.124 [http-nio-8080-exec-6] WARN  o.r.C.Server - Error while handling an HTTP server call
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed**

Sometimes, not always, I found the log:

**11:29:21.173 [http-nio-8080-exec-9] WARN  c.a.s.s.i.S3AbortableInputStream - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.**

Its like if the app would be closing the connections to aws s3 bucket before the requests had been finished. 

I attach the complete log:

[cis-error-tomcat-log.txt](https://github.com/medusa-project/cantaloupe/files/1884138/cis-error-tomcat-log.txt)

Thanks to all,
Regards.

**Comment by adolski** [comment]
Hi @dmajano, 

Thanks for reporting this and posting a log. It looks like things are working up until this point:

```
15:02:21.105 [http-nio-8080-exec-6] DEBUG e.i.l.c.r.ImageRepresentation - write(): Incompatible color conversion
```

Right before this, Java2dProcessor was set up to write to the response and derivative cache simultaneously, but then it encountered this image it couldn't process, so it failed and wrote zero bytes to both. AmazonS3Cache then uploaded this zero-byte object to the cache bucket, which is a separate bug that will need to get fixed.

I'm going to guess that if you tried to load this image (`p/07/07/169317.jpg`) from some other resolver, like FilesystemResolver, it wouldn't work from there, either -- maybe it has CMYK/YCCK color or an incompatible embedded ICC profile? Unfortunately, the underlying Image I/O plugin that Java2dProcessor uses to read JPEGs -- `com.sun.imageio.plugins.jpeg.JPEGImageReader` -- is very strict.

I'd be interested in taking a look at this JPEG if you are able to share it...

**Comment by adolski** [comment]
Also, about that other log message -- it's not related to the above, but I can explain it briefly:
```
11:29:21.173 [http-nio-8080-exec-9] WARN c.a.s.s.i.S3AbortableInputStream - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
```
The AWS HTTP client wants you (or rather me, the developer) to fully consume response HTTP entities so that it can reuse the connections in the pool. But, it's hard to ensure that this happens all of the time, because what if a user is reading an image that is 500MB and presses the stop button after only 10MB have been downloaded? The application doesn't want to have to read the remaining 490MB for no reason, so it closes the connection and the AWS client complains. 🤷‍♂️

**Comment by dmajano** [comment]
Thank you very much @adolski . To workaround this issue I have changed the jpg Processor to "ImageMagick" and it's working good!

**Comment by adolski** [comment]
Agreed, good to hear that it's working now.
