### ISSUE TITLE
Make the ContainerCredentialProvider available for ECS deploys?

### ISSUE THREAD

**Issue by eefahy** [medusa-project/cantaloupe#215]
We are trying to deploy cantaloupe in ECS that leverages container credentials for access to S3. Currently, the deploy is returning a 500 error as it's not able to pick up the container credentials in the provider chain. Looking [here](https://github.com/medusa-project/cantaloupe/blob/24daaaacbb8d1e69863496183f6e0f88b5486f7d/src/main/java/edu/illinois/library/cantaloupe/util/AWSClientBuilder.java#L107-L110) I'm not seeing the container provider as an option? Is that intentional?

refs:
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html (see no. 4 under default provider chain)
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/ContainerCredentialsProvider.html

Thanks for your help.

**Comment by adolski** [comment]
Not intentional, I'm happy to add this. It looks like `ContainerCredentialsProvider()` gets a URI path from the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable, and appends it to `http://169.254.170.2`. But it's deprecated, so the other constructor would have to be used, which requires a custom CredentialsEndpointProvider -- so `CredentialsEndpointProvider.getCredentialsEndpoint()` would probably try to read from some new configuration key, or fall back to the behavior of the other constructor if not set?

**Comment by eefahy** [comment]
Thanks for the quick reply & sorry for my delay. Ah, yes, I see. I’m confused about that function being deprecated to be honest. I can confirm that the relative uri env var is set on my container though. What about using the default credential provider chain instead of each individual provider? https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by eefahy** [comment]
If you want to set individual providers than I think this is the one you actually want: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.html

The caveat being that the keys will expire every 24 hours (I think) so that refresh method is most likely also required.

**Comment by adolski** [comment]
This is now available on `develop` -- I held off on the auto-refreshing because I can't find any documentation that says it's explicitly necessary, so I think the S3 client might be handling that itself, although the docs don't mention that, either. Can always add it if necessary.

**Comment by eefahy** [comment]
Thanks so much! I will test this out tomorrow and will close this issue once I confirm it refreshes as expected.

**Comment by adolski** [comment]
Any luck, @eefahy ?
