### ISSUE TITLE
Cannot run program "/usr/bin/opj_dump/opj_dump": error=20, Not a directory

### ISSUE THREAD

**Issue by michaelw3** [medusa-project/cantaloupe#216]
i added the path to the `opj_dump` in the `/usr/bin/` folder but somehow i continue to get this message.
i tried to change it to `/usr/bin` and `/usr/bin/opj_dump` but non of them works.
even leaving it without the path it continues to look in the same folder `/usr/bin/opj_dump/opj_dump`.

thanks for any help

**Comment by michaelw3** [comment]
**UPDATE** 
somehow after entering the path into the web ADMIN it started to work and know i get this warning 
`This version of opj_decompress doesn't support quiet mode. Please upgrade OpenJPEG to version 2.2.0 or later.`
but only got 2.1 from the opensuse distributor. should i build from source or can i use it this way?

**Comment by adolski** [comment]
Hi @michaelw3,

Here is the background on the recommendation for OpenJPEG 2.2.0: https://github.com/medusa-project/cantaloupe/issues/111

Short summary is that, for some images, `opj_decompress` < 2.2.0 writes both decoded image data and debug messages to the same stream, corrupting them.

**Comment by michaelw3** [comment]
hi @adolski thanks a lot for the answer.
didn't quite understood everything there but i guess that the problem that i have know is exactly the problem you mentioned, some pics aren't shown.

i guess i'll have to install the newer version of OpenJpeg

**Comment by michaelw3** [comment]
ok, upgrading the openjpeg library did solve the problem thanks @adolski !
