### ISSUE TITLE
info.json: https protocol in @id

### ISSUE THREAD

**Issue by mmatela** [medusa-project/cantaloupe#222]
I'm downloading a URL like this: https://my-domain/iiif/my-image/info.json
In Cantaloupe 3.4.2, the response starts with
`{"@context":"http://iiif.io/api/image/2/context.json","@id":"https://my-domain/iiif/my-image",`
In Cantaloupe 3.4.3 nad 4.0 the response starts with
`{"@context":"http://iiif.io/api/image/2/context.json","@id":"http://my-domain/iiif/my-image",`
The protocol of `@id` URL is not secure, which I think is not correct.

I didn't check if any other places in JSON responses are affected as well.

My configuration is very close to default, with `FilesystemSource.BasicLookupStrategy`, processing TIFF images.

**Comment by jweisman** [comment]
Chiming in here since this problem was caused by my PR #217. I opened another PR #224 which should address this. Teaches me to run my development environment in HTTPS as well.... :(

**Comment by adolski** [comment]
Thanks for reporting this, @mmatela, and thanks for taking care of it, @jweisman. I'll release a 3.4.4 sometime soon.
