### ISSUE TITLE
Issue  with decoding size information from JP2s

### ISSUE THREAD

**Issue by cbeer** [medusa-project/cantaloupe#226]
After updating to Cantaloupe 4.0, we're seeing certain JP2 images fail to get the right metadata
 (e.g. https://stacks.stanford.edu/file/ky226pt1201/406_001_R_NC_46.jp2)

```
07:32:18.338 [ajp-apr-8009-exec-1] DEBUG e.i.l.c.p.c.JPEG2000MetadataReader - size: 0x0; tileSize: 0x0; 0 components; 0 bpc; 0 DWT levels
07:32:18.358 [ajp-apr-8009-exec-1] TRACE e.i.l.c.p.AbstractImageIOProcessor - readImageInfo(): {"mediaType":"image/jp2","numResolutions":1,"images":[{"width":0,"height":0,"tileWidth":0,"tileHeight":0,"orientation":1}]}
``` 

But using `kdu_jp2info`, we can see:

```
<JP2_family_file>
  <ftyp name="file-type box" header="8" body="12" pos="12">
    <brand> "jp2_" 0x6A703220 </brand>
    <minor_version> 0 </minor_version>
    <compatible_brand> "jp2_" 0x6A703220 </compatible_brand>
  </ftyp>
  <jp2h name="JP2-header box" header="8" body="272,873" pos="32">
    <ihdr name="image-header box" header="8" body="14" pos="40"></ihdr>
    <colr name="colour box" header="8" body="272,843" pos="62"></colr>
  </jp2h>
  <jp2c name="contiguous-codestream box" header="8" body="rubber" pos="272,913">
    <codestream>
      <width> 5428 </width>
      <height> 7228 </height>
      <components> 3 </components>
      <tiles> 165 </tiles>
    </codestream>
  </jp2c>
</JP2_family_file>
```

Any thoughts?

**Comment by adolski** [comment]
Probably a bug... are you able to share the image?

**Comment by cbeer** [comment]
I've linked one in my report:

https://stacks.stanford.edu/file/ky226pt1201/406_001_R_NC_46.jp2

and we have plenty more like it:

https://stacks.stanford.edu/file/ky226pt1201/406_002_R_NC_46.jp2
https://stacks.stanford.edu/file/ky226pt1201/406_003_R_NC_46.jp2
https://stacks.stanford.edu/file/ky226pt1201/406_004_R_NC_46.jp2
(etc, etc)

**Comment by adolski** [comment]
Thanks, I will take a look

**Comment by cbeer** [comment]
Perhaps interestingly, similarly generated JP2s are working fine: 
https://stacks.stanford.edu/file/rj081wk6820/492_001_NC_46.jp2

**Comment by adolski** [comment]
FWIW [jpylyzer](http://jpylyzer.openpreservation.org) reports `<isValidJP2>False</isValidJP2>` for 406_001_R_NC_46.jp2

I'd still like to be able to be able to handle it properly though...

**Comment by cbeer** [comment]
It's interesting that jpylyzer reports the same thing about https://stacks.stanford.edu/file/rj081wk6820/492_001_NC_46.jp2 (which works fine in Cantaloupe).

**Comment by adolski** [comment]
The above commit ought to take care of this. The jpylyzer warning is a red herring in this case.

**Comment by cbeer** [comment]
Thanks; I can confirm this fixes our problem.
