### ISSUE TITLE
png files being output as jpg

### ISSUE THREAD

**Issue by ogloke** [medusa-project/cantaloupe#227]
I'm having a problem with png files being converted to jpg files and thier losing transparency. If I call the url https://trin-digital-library.trin.cam.ac.uk/iiif/2/NQ.10.145%2Fp056.png/full/full/0/default.png there's no problem the image is returned as a png. However when I view the image in Mirador or Universal Viewer it is displayed as a jpeg with filled in background. 
Here is what Cantaloupe is doing when I look at the image in Mirador
`11:42:47.814 [qtp519569038-167] DEBUG e.i.l.c.p.c.PNGImageReader - ImageIO plugin preferences: com.sun.imageio.plugins.png.PNGImageReader
11:42:47.814 [qtp519569038-167] DEBUG e.i.l.c.p.c.PNGImageReader - Using com.sun.imageio.plugins.png.PNGImageReader
11:42:47.814 [qtp519569038-167] DEBUG e.i.l.c.p.c.PNGImageReader - Ignoring metadata? true
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.p.Java2DUtil - scale(): scaled 1803x1786 image to 113x112 using a BiCubic filter in 109 msec
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.p.c.JPEGImageWriter - ImageIO plugin preferences: com.sun.imageio.plugins.jpeg.JPEGImageWriter
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.p.c.JPEGImageWriter - Using com.sun.imageio.plugins.jpeg.JPEGImageWriter
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.p.Java2DUtil - removeAlpha(): executed in 0 msec
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.p.c.JPEGImageWriter - Quality: 100; progressive: true
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.r.ImageRepresentation - Java2dProcessor processed in 265 msec: NQ.10.145/p056.png_scale:113,,bicubic_encode:jpg_JPEG_interlace_#FFFFFF_8
11:42:48.032 [qtp519569038-148] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): closing stream for NQ.10.145/p056.png_scale:113,,bicubic_encode:jpg_JPEG_interlace_#FFFFFF_8`

Is there a way to get it to write a png instead of jpeg for the output?

**Comment by adolski** [comment]
Hi @ogloke,

When I load that URL, the output is a PNG with alpha as expected (red triangle + transparent background).

Note that the log excerpt contains two different thread IDs (`qtp519569038-167` and `qtp519569038-148`) which appear to be showing an earlier part of one request and a later part of a different request, so it's not really picturing what's going on.

The way to request a different format is to change the URI path extension:

* PNG: https://trin-digital-library.trin.cam.ac.uk/iiif/2/NQ.10.145%2Fp056.png/full/full/0/default.png
* JPEG: https://trin-digital-library.trin.cam.ac.uk/iiif/2/NQ.10.145%2Fp056.png/full/full/0/default.jpg

**Comment by ogloke** [comment]
Hi @adolski ,
Thanks for the reply.
What I'm trying to do with the png is to overlay it on another image.
An example is p056 of http://sites.trin.cam.ac.uk/manuscripts/testsite/mirador.php?n=NQ.10.145 
If you turn on the layer in the left hand side panel you get the the red triangle but a white background.
The server is changing the png to jpeg using e.i.l.c.p.c.JPEGImageWriter even though the URI path extension is set to PNG. I'm confused as to why this is.

**Comment by adolski** [comment]
I don't think the server is changing the PNG to a JPEG, I think Mirador & UV are requesting a JPEG where you don't want them to.

For example, if you have your web browser's network inspector open while going through your example with p056, you can see it requesting several JPEG versions of your PNG, even though it requests the thumbnail in the "layers" section as a PNG:

![untitled](https://user-images.githubusercontent.com/6854505/43088878-e4208bca-8e68-11e8-8fc6-0080385ce17b.png)

So I think this is a Mirador issue and the similar behavior in UV would be a UV issue.

**Comment by ogloke** [comment]
That's interesting, I'll investigate further on that side of things. Thanks for your help.
