### ISSUE TITLE
KakaduDemoProcessor formats regions incorrectly

### ISSUE THREAD

**Issue by x1rskarw** [medusa-project/cantaloupe#235]
When running on a Windows machine with German locale settings, the KakaduDemoProcessor formats the region specification using the default locale which results in the following region specification being generated: "{0,0},{0,32114,0,31175}".

kdu_expand chokes on it:
Kakadu Error:
The `-region' argument requires a set of coordinates of the form,
"{<top>,<left>},{<height>,<width>}". All quantities must be real numbers in the
range 0 to 1.

Cantaloupe must be started with a different locale explicitely specified, ie using -Duser.language=en_US in order for the JPEG2000 support to work.

The KakaduDemoProcessor should probably pass another Locale to the DecimalFormat constructor or possibly an appropriate DecimalFormatSymbols instance.

**Comment by adolski** [comment]
Thanks for investigating this, @x1rskarw . The above commit (on release/4.0 branch) ought to fix it.
