### ISSUE TITLE
Inconsistent synchronization in HttpSource

### ISSUE THREAD

**Issue by x1rskarw** [medusa-project/cantaloupe#236]
This is rather minor but getHTTPClient() is a synchronized static method and as such uses the class instance's monitor. In contract, the overridden shutdown() method is a synchronized instance method using the respective instance's monitor. In effect, the jettyClient is not protected at all. 
Instead, the cleanup code should be refactored into a synchronized static method and that method should be called from shutdown().

**Comment by adolski** [comment]
Thanks for reporting.
