### ISSUE TITLE
Redaction block ignored if larger than requested size/scale

### ISSUE THREAD

**Issue by Ra1phM** [medusa-project/cantaloupe#237]
Hello,

While using the redaction feature, I have encountered a bug where redaction blocks that have a position larger than the request file size or where the scale is smaller than certain block coordinates are not drawn anymore.

I return 5 blocks in the redaction function:

    def redactions(options = {})
         redactions = []

        # TEST
        redactions << {'x' => 10, 'y' => 10, 'width' => 100, 'height' => 50}          # B10
        redactions << {'x' => 100, 'y' => 100, 'width' => 100, 'height' => 50}      # B100
        redactions << {'x' => 500, 'y' => 500, 'width' => 100, 'height' => 50}      # B500
        redactions << {'x' => 1000, 'y' => 1000, 'width' => 100, 'height' => 50}  # B1000
        redactions << {'x' => 2000, 'y' => 2000, 'width' => 100, 'height' => 50}  # B2000
        redactions << {'x' => 3000, 'y' => 3000, 'width' => 100, 'height' => 50}  # B3000

        return redactions
      end

**My settings:**

* Original Image: TIFF (line-based)
* Original Image Size: 3650x5079
* Processor: Java2dProcessor

# Case 1:
Block who have a position (x,y) larger than the requested size are not drawn.

## Example 1 - /full/full/ - OK:
When I request the full image at full scale, all blocks are drawn

## Example 2 - /full/3000,/ - NOT OK
The full image is request at scale 3000, but the block B3000 is not drawn.

## Example 3 - /full/2000,/ - NOT OK
The full image is request at scale 2000, but the blocks B3000 and B2000 are not drawn.

Etc. The more I scale down, the more blocks are not drawn and thus information is "leaked"

# Case 2:
Tiles starting at a position different than (0,0) and larger than a certain value.

## Example 4 - /0,0,2100,2100/full/ - OK
The tile correctly contains the blocks B10, B100, B500, B1000 and B2000

## Example 5 - /15,15,2100,2100/full/ - OK
The tile correctly contains the blocks B10, B100, B500, B1000 and B2000

## Example 5 - /15,15,2100,2100/1000,/ - NOT OK
The tile correctly contains the blocks B10, B100, B500 but does not contain B1000 and B2000

## Example 6 - /1800,1800,2000,2000/full/ - NOT OK
The tile does not contain the redaction block B2000, B3000

## Example 7 - /1800,1800,3000,3000/full/ - NOT OK
Same as example 6, the tile does not contain the redaction block B2000, B3000

Any help would be appreciated,

Best regards,

Ralph

**Comment by adolski** [comment]
Thanks for reporting this, @Ra1phM . This should be fixed now on the `release/4.0` branch. Feel free to reopen if you  notice any more problems.

**Comment by Ra1phM** [comment]
Thank you very much. Seem to work perfectly now.
