### ISSUE TITLE
Performance Cantaloupe

### ISSUE THREAD

**Issue by valeriofinazzo** [medusa-project/cantaloupe#245]
Hi everyone,
I'm having a performance problem on Cantaloupe in production. With simultaneous calls with images of about 15 megs in jpg format, the memory has a peak and after a while the system stops. What would be the recommended configuration to get the best performance and avoid blocking?
As the problem occurs with the management of the tiles would it be possible to preload the cache to reduce their processing?
The version in prod is 3.3
thank you

**Comment by adolski** [comment]
Hi @valeriofinazzo,

I don't know about the system stopping, but 15 MB JPEGs will be fairly expensive (CPU+memory) to serve. See this issue: https://github.com/medusa-project/cantaloupe/issues/239
