### ISSUE TITLE
Version 1 endpoint info.json should list quality 'grey', not 'gray'; v1 endpoint should serve 'grey' quality

### ISSUE THREAD

**Issue by lutzhelm** [medusa-project/cantaloupe#249]
[Image API version 1.1](https://iiif.io/api/image/1.1/#4-4-quality) lists `grey` as valid value; the [changelog of version 2.0](https://iiif.io/api/image/2.0/change-log/#renamed-qualities) mentions the change to `gray`. The server should also serve `grey` quality images for version 1 - currently requests for `grey` result in a 400 Bad Request error.

I don't know how relevant this is and which clients are aware of that seemingly tiny difference but I wanted to mention it anyway.

**Comment by adolski** [comment]
Good catch, @lutzhelm! Thanks for reporting.
