### ISSUE TITLE
GraphicsMagick Processor is not envoked

### ISSUE THREAD

**Issue by ghohmann** [medusa-project/cantaloupe#252]
I am aware of issues #62 and #135, but nevertheless I can't get my images processed by GraphicsMagick.
My setup (fresh minimal installation):
```
Ubuntu 18.04.1 LTS
GraphicsMagick 1.3.28
Cantaloupe 4.0.2 (standalone)
```
I created a user (group: users) to run cantaloupe standalone. The user has access to "gm". Running "gm version" by that user says that webp is supported. 

Cantaloupe itself works like a charm. Source is a folder with ~6.000 JPGs. I tried to handle the webp output with GraphicsMagick but with no luck. The crucial parts of my properties-file look like this:
```
# These extension-specific definitions are optional.
processor.avi = FfmpegProcessor
processor.bmp = GraphicsMagickProcessor
processor.dcm = ImageMagickProcessor
processor.flv = FfmpegProcessor
processor.gif =
processor.jp2 = KakaduNativeProcessor
processor.jpg =
processor.mov = FfmpegProcessor
processor.mp4 = FfmpegProcessor
processor.mpg = FfmpegProcessor
processor.pdf = PdfBoxProcessor
processor.png =
processor.tif =
processor.webm = FfmpegProcessor
processor.webp = GraphicsMagickProcessor

# Fall back to this processor for any formats not assigned above.
processor.fallback = Java2dProcessor
```
First I tried to add GM to the library path using my execute-script:
```
#!/bin/bash
export LD_LIBRARY_PATH=/opt/cantaloupe/deps/Linux-x86-64/lib:/usr/bin:$LD_LIBRARY_PATH
java -Dcantaloupe.config=/opt/cantaloupe/cantaloupe.properties -Xmx2g -jar /opt/cantaloupe/cantaloupe-4.0.2.war
```
After that didn't work, I also added the GM path to the properties file:
```
# !! Optional absolute path of the directory containing the GraphicsMagick
# binary. Overrides the PATH.
GraphicsMagickProcessor.path_to_binaries = /usr/bin
```
But no matter what I try, cantaloupe does not seem to even recognize GM.
If I try to retrieve an image as webp I get:
```
415 Unsupported Media Type
Java2dProcessor does not support the "WebP" output format
edu.illinois.library.cantaloupe.processor.UnsupportedOutputFormatException: Java2dProcessor does not support the "WebP" output format
```
As you see cantaloupe uses the fallback processor and not GM. It's the same if I try to attach the GM processor to other image formats.

Any ideas?

**Comment by adolski** [comment]
Hi @ghohmann,

With the `processor.[extension]` keys, `[extension]` refers to a source format. So since your source images are JPEGs, and `processor.jpg` is not set, `processor.fallback = Java2dProcessor` is used, and you are limited to the output formats supported by that processor.

**Comment by ghohmann** [comment]
Hi @adolski 
I totally misunderstood the semantics of these settings.

I thought it is about setting a processor to be responsible for generating the given format _from_ the source. Now I just attached `processor.jpg = GraphicsMagickProcessor`and cantaloupe is able to generate all output formats that GraphicsMagick supports, even `.webp`. And it's also much faster now.

Thank you very much!

**Comment by ghohmann** [comment]
No I ran into another problem:
After some minutes using GM without a problem, i suddenly got an "broken pipe" error by requesting an image. I seems that GM is not able to find my images. Strange.

This is the log:
`10:27:27.073 [qtp2051853139-43] DEBUG e.i.l.c.r.AbstractResource - Identifier requested: PT_00001_05 -> decoded: PT_00001_05 -> slashes substituted: PT_00001_05
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/83/04bd830b90a1345f1bf378865179b4b4.json
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.s.FilesystemSource - Resolved PT_00001_05 to /data/media/img/arc/PT-001/PT_00001_05.jpg
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.p.ProcessorConnector - FileSource -> StreamProcessor connection between FilesystemSource and GraphicsMagickProcessor
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/83/04bd830b90a1345f1bf378865179b4b4.json
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.p.GraphicsMagickProcessor - readImageInfo(): invoking gm identify -ping -format %w%h%[EXIF:Orientation] jpg:-
10:27:27.081 [qtp2051853139-43] ERROR o.r.C.RestletApplication - Exception or error caught in server resource
`

There seems to be something wrong with the caching mechanism:
`getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/83/04bd830b90a1345f1bf378865179b4b4.json`

When I switch back to the 'fallbackJava2dProcessor', everything works fine.
When I switch back to GM again(!), I can access the _same_ file even in other output formats.

Does anyone noticed the same behaviour?

**Comment by ghohmann** [comment]
Additional note:
I just tried using Imagemagick instead. Works fine so far, just a bit slower.
So is this a GM problem then?

**Comment by adolski** [comment]
Hi @ghohmann , would you mind creating a new issue for this, and closing this one?

Also, when pasting log messages into an issue, please paste a full request from start to end, including any exception traces, with `log.application.level = trace`, and surround the text with three backticks (`) on the first & last line in order to preserve line breaks:

```
line
line
line
```

**Comment by ghohmann** [comment]
> would you mind creating a new issue for this, and closing this one?
Sure! Done at #256
