### ISSUE TITLE
Avoiding %2F in subfolder URLs

### ISSUE THREAD

**Issue by lldata** [medusa-project/cantaloupe#262]
Hi,

I can reference an image in a subfolder with /iiif/2/subfolder%2Fimg.jpg 
How can I configure cantaloupe to use /iiif/2/subfolder/img.jpg ?

I tried slash_substitute = /

Is is possible to just disable slash substitution?

Thanks

**Comment by adolski** [comment]
Hi @lldata ,

The IIIF Image API doesn't allow unencoded slashes in identifiers: https://iiif.io/api/image/2.1/#identifier

**Comment by lldata** [comment]
Ok. I understand. A spec i a spec.

It is just that the tomcat server we use as a api gateway in front of canteloupe rejects requests with %2F as directory traversal requests. But I guess we can find some kind of workaround for that...
