### ISSUE TITLE
X-Forwarded-Port does not default to 80 as documented

### ISSUE THREAD

**Issue by lldata** [medusa-project/cantaloupe#264]
We are working on a cantaloupe installation behind a couple af gateway servers, so we are playing around with the X-Forwarded-* headers.

Running the local example on port 8182 with the following requests:

Correct:
GET http://localhost:8182/iiif/2/airbus.jpg/info.json

Response snippet:
  "@id": "http://localhost:8182/iiif/2/airbus.jpg",

Correct:
GET http://localhost:8182/iiif/2/airbus.jpg/info.json
X-Forwarded-Host: myserver
X-Forwarded-Port: 123

Response snippet:
  "@id": "http://myserver:123/iiif/2/airbus.jpg",

Incorrect:
GET http://localhost:8182/iiif/2/airbus.jpg/info.json
X-Forwarded-Host: myserver

  "@id": "http://myserver:8182/iiif/2/airbus.jpg",

In the last request I would expect the @id url to be:
  "@id": "http://myserver/iiif/2/airbus.jpg",

as documented here https://medusa-project.github.io/cantaloupe/manual/4.0/deployment.html

**Comment by lldata** [comment]
The code in question is this? 
https://github.com/medusa-project/cantaloupe/blob/a364e15fef05d632dda3f1ce068cbc16eacdd5c9/src/main/java/edu/illinois/library/cantaloupe/resource/AbstractResource.java#L500

I suspect the port should initially be hardcoded to "80" here, if the x-forwarded-host is set.

**Comment by adolski** [comment]
Thanks for reporting this, @lldata . I think the docs are wrong here, or at least not clear. The workaround for the time being is to supply an `X-Forwarded-Port`.
