### ISSUE TITLE
Response header missing Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by dtcaldwell** [medusa-project/cantaloupe#266]
Trying to run Cantaloupe with standalone webserver and http:. The server is not sending the "Access-Control-Allow-Origin: *" header response, which is preventing applications not on my server from using images I'm serving. How do I get the web server to include this header?
----------------

The IIIF Image API 2.1.1 says:
"Servers should send the Access-Control-Allow-Origin header with the value * in response to information requests. The syntax is shown below and is described in the CORS specification. This header is required in order to allow the JSON responses to be used by Web applications hosted on different servers.
Access-Control-Allow-Origin: *

But the standalone webserver with Cantaloupe is not returning that header. (Header below:

Cache-Control | max-age=2592000, public, no-transform
-- | --
Content-Type | application/json;charset=utf-8
Date | Sun, 03 Feb 2019 19:07:09 GMT
Server | Restlet-Framework/2.3.11
Transfer-Encoding | chunked
Vary | Accept-Charset, Accept-Encoding, Accept-Language, Origin, Accept
X-Powered-By | Cantaloupe/4.0.3
----------
---------------------
I ran the IIIF validator at https://iiif.io/api/image/validator/.  All tests passed except:
Cross Origin Headers
Elapsed time (ms): 151
    got: http://iiif.io/
    expected: *
    url: http://206.189.226.9:8182/iiif/2/test.png/info.json
    type: CORS

**Comment by adolski** [comment]
Hi @dtcaldwell,

Through version 4.0.x, Cantaloupe uses the Restlet framework, which refuses to add `Access-Control-Allow-Origin` in the absence of an `Origin` header in the request. I believe that this is based on its interpretation of sections 6.1 and 6.2 of the [W3C CORS spec](https://www.w3.org/TR/access-control/).

In version 4.1, Restlet has been removed and `Access-Control-Allow-Origin` is always present, to align more closely with the IIIF Image API.

So, the workaround until 4.1 arrives is to include an `Origin` header in requests.

**Comment by NbtKmy** [comment]
Hi @adolski,
I'm using the version 4.0.2 and thinking to upgrade it into the version 4.1.1. 
What should i do, if I want to activate CORS with Cantaloupe 4.1.x? In the configuration file I've not found the configuration keys for enabling CORS.  
Does the sentence "Access-Control-Allow-Origin is always present" mean that the server enables alwalys CORS without any configuration change? It'd be so nice...

**Comment by adolski** [comment]
That's correct--Image API responses in 4.1 always include the `Access-Control-Allow-Origin` header with no configuration necessary.

**Comment by NbtKmy** [comment]
So great! Many thanks!
