### ISSUE TITLE
publish a roadmap for the 4.1 release

### ISSUE THREAD

**Issue by hardyoyo** [medusa-project/cantaloupe#271]
I can see there was a previous request for a project-wide roadmap with issue #50, this is a similar request, but specific to the upcoming 4.1 release. I'd like to request that a roadmap towards the 4.1 release be created, ideally with a projected release date. If there are issues/features/fixes you'd like to include in that milestone, I'd like to offer to help. I'm sure others would as well.

As-is, the current develop branch has a number of AWS-related features we'd like to be able to use now. We'd love to be able to use a 4.1-rc version, if it existed, instead of recompiling the develop branch. However, that's getting ahead... if we could have a roadmap for how we get to that release candidate, we can help you get there. Thanks for all your hard work on this project, and your consideration of this request!

**Comment by adolski** [comment]
Hi @hardyoyo,

I can't commit to any dates, but I can tell you that 4.1 is close to being ready. I might want to add a couple more things. But I have a lot of other projects going on right now and not much time for this one.

FYI, `develop` always tracks the next major or minor version, and never contains anything that won't go into that, so it's "safe" to use as a "4.1-rc" and all of the documentation on that branch is current, including `CHANGES.md` and `website/upgrade.html` (soon to become `UPGRADING.md`).

The best way to help (for 4.1) is probably just test driving and reporting or sending PRs for any issues.
