### ISSUE TITLE
AccessDeniedException when accessing HTTPS source with authorization

### ISSUE THREAD

**Issue by bertspaan** [medusa-project/cantaloupe#272]
I'm using Cantaloupe for a project with the City Archives of Amsterdam.

I'm running Cantaloupe `4.1-SNAPSHOT` from a Docker container, and I can access images using HTTPS with authorization. (I've also used version 4.0.3, but I switched to the develop branch to see if a new version would maybe solve this issue — it didn't.)

This the relevant part of the delegate script:

```rb
def httpsource_resource_info(options = {})
    namespace, identifier = identifier_parts()

    case namespace
    when 'edepot' then
      uri = URI.decode(identifier)

      return {
        "uri" => "https://bwt.uitplaatsing.hcp-a.basis.lan/rest/#{uri}",
        "headers" => {
          "Authorization" => ENV['HCP_AUTHORIZATION']
        }
      }
    end
  end
```

The delegate script correctly translates the identifier in to URI `https://bwt.uitplaatsing.hcp-a.basis.lan/rest/SA/00037/SA00000244_00002.jpg` and the `HCP_AUTHORIZATION` environment variable is present.

However, the request leads to an `AccessDeniedException`:

![image](https://user-images.githubusercontent.com/1194896/53729305-330b8700-3e75-11e9-9ea5-55a5a719c58a.png)

When I use cURL in the same container where Cantaloupe is running, everything works correctly:

    curl -k -i -H "Authorization: $HCP_AUTHORIZATION" https://bwt.uitplaatsing.hcp-a.basis.lan/rest/SA/00037/SA00000244_00002.jpg

I did set the `HttpSource.trust_all_certs = true` property in `cantaloupe.properties`.

Do you have any idea what might be the difference between a `GET` request issued by Cantaloupe, and one done by cURL?

**Comment by adolski** [comment]
Hi @bertspaan,

I can't reproduce this. Here is my HttpSource delegate method:

```ruby
  def httpsource_resource_info(options = {})
    {
        'uri' => 'http://images.127.0.0.1.xip.io/' + context['identifier'],
        'headers' => {
            'Authorization' => 'open sesame'
        }
    }
  end
```
When I set the log level to `trace`, I see these lines:

```
07:49:47.723 [qtp1033638837-23] DEBUG e.i.l.c.s.HttpSource - Requesting HEAD http://images.127.0.0.1.xip.io/f50.jpg (extra headers: Authorization: open sesame)
07:49:47.978 [qtp1033638837-23] TRACE e.i.l.c.s.HttpSource - Requesting GET http://images.127.0.0.1.xip.io/f50.jpg (extra headers: Authorization: open sesame)
```
Those lists of extra headers are not technically coming from the HTTP client, merely they are lists of what is being given to the HTTP client, so I use Wireshark to confirm that they are being sent in both the HEAD and GET requests:

![screen shot 2019-03-04 at 7 52 23 am](https://user-images.githubusercontent.com/6854505/53737806-25450a00-3e53-11e9-9a87-3b3bbae36f14.png)
![screen shot 2019-03-04 at 7 52 01 am](https://user-images.githubusercontent.com/6854505/53737810-27a76400-3e53-11e9-8376-c1044b4589a4.png)

**Comment by bertspaan** [comment]
It turns out Jetty disallows a certain set of cipher suites by default (probably older and insecure cipher suites). The server I need Cantaloupe to get images from is using an older version of TLS with older ciphers.

To disable this check, I can add the following line to the `getHTTPClient` function of `HttpSource.java`:

```java
sslContextFactory.setExcludeCipherSuites("");
```

I've started working on a small PR to include this change: https://github.com/medusa-project/cantaloupe/compare/develop...Amsterdam:develop, it only needs a few tests. If you think this is a useful PR, let me know, and I can add the tests.

**Comment by adolski** [comment]
Thanks for looking into this. Could the `HttpSource.trust_all_certs` key work around this problem?

**Comment by bertspaan** [comment]
No, I tried that earlier, setting that key to `true` was not enough.

**Comment by adolski** [comment]
I'm just trying to decide whether a new config key is needed for this -- one which seems like it would be rarely used. Would something like this work instead:

```java
final Configuration config = Configuration.getInstance();
final boolean trustAllCerts = config.getBoolean(
        Key.HTTPSOURCE_TRUST_ALL_CERTS, false);
SslContextFactory sslContextFactory =
        new SslContextFactory(trustAllCerts);
if (trustAllCerts) {
    sslContextFactory.setExcludeCipherSuites(excludeCipherSuites.split(","));
}
```

**Comment by bertspaan** [comment]
Yes, that would work (where would `excludeCipherSuites` come from then?), although I cannot predict whether always accepting all cipher suites when `trustAllCerts` is enabled has any drawbacks.

**Comment by adolski** [comment]
Okay, yeah, I think that will work. But since cipher suites aren't certs, How about renaming the `HttpSource.trust_all_certs` key to `HttpSource.allow_insecure`:
```java
final Configuration config = Configuration.getInstance();
final boolean allowInsecure = config.getBoolean(
        Key.HTTPSOURCE_ALLOW_INSECURE, false); // replaces TRUST_ALL_CERTS
SslContextFactory sslContextFactory =
        new SslContextFactory(allowInsecure);
if (allowInsecure) {
    sslContextFactory.setExcludeCipherSuites("");
}
```
When enabled, untrusted certs are allowed as well as all cipher suites.

Does that sound like a plan? I'm happy to accept a PR for this, otherwise I'll do it, but it may take a while.

**Comment by bertspaan** [comment]
OK! I'll work on a PR!

**Comment by adolski** [comment]
@bertspaan I'll take care of this

**Comment by bertspaan** [comment]
Thanks!!!
