### ISSUE TITLE
4.1 X-Forwarded-Path header application

### ISSUE THREAD

**Issue by adam-vessey** [medusa-project/cantaloupe#278]
The appending of `getPath()` at https://github.com/medusa-project/cantaloupe/blob/3def2dfd35e93f15e6067f7a80b2aa578492fd05/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java#L139 / https://github.com/medusa-project/cantaloupe/blob/df4262bd0b934067c52995de568d87197e0c034d/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java#L135 appears to break the use of the `X-Forwarded-Path` headers.

```diff
diff --git a/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java b/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java
index 64811740c..5d349c3d1 100644
--- a/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java
+++ b/src/main/java/edu/illinois/library/cantaloupe/http/Reference.java
@@ -136,7 +136,7 @@ public final class Reference {
         final String pathHeader = headers.getFirstValue("X-Forwarded-Path", "");
         if (!pathHeader.isEmpty()) {
             String path = pathHeader.split(",")[0].trim();
-            setPath(StringUtils.stripEnd(path, "/") + getPath());
+            setPath(StringUtils.stripEnd(path, "/"));
         }
     }

```

did the trick for me.

**Comment by adolski** [comment]
Hi @adam-vessey ,

I think X-Forwarded-Path is supposed to contain the "path to the application," and not a full path, e.g.:

https://github.com/medusa-project/cantaloupe/blob/3def2dfd35e93f15e6067f7a80b2aa578492fd05/src/test/java/edu/illinois/library/cantaloupe/http/ReferenceTest.java#L172-L179

**Comment by adam-vessey** [comment]
I... think we're in agreement there; however, the definition of the "path to the application" is complex... in reverse proxy configurations, you might expect to be able to effective change _where_ the application is, or hit a specific endpoint inside the application, to expose as the "application"... Our present proxy configuration we've been using up to now is something rather like:
```
  <Location "/iiif/2">
    Require all granted
    RequestHeader set X-Forwarded-Proto http
    RequestHeader set X-Forwarded-Port 80
    RequestHeader set X-Forwarded-Path /
    ProxyPass http://hostname.local:8080/cantaloupe/iiif/2
    ProxyPassReverse http://hostname.local:8080/cantaloupe/iiif/2
  </Location>
```

... effectively, only allowing access to the IIIF v2 endpoint (with Cantaloupe running inside of Tomcat).

With the appending as described initially, requests such as `http://hostname.local/iiif/2/my-thing/info.json` now yield `@id` values like `http://hostname.local/cantaloupe/iiif/2/my-thing`, which no longer hits the reverse proxy.

**Comment by adolski** [comment]
It sounds like this header wasn't working correctly up until now but your setup was depending on that incorrectness. Maybe what you need is a more specific variant of X-Forwarded-Path, like an X-Forwarded-Full-Path or X-Forwarded-Application-Path or something?

**Comment by adam-vessey** [comment]
I'm... not sure I understand the use-case for appending the application path... as I understand it, all these `X-Forwarded-*` headers exposed here are essentially an alternative to rolling a "mod_proxy_json" or similar (in the style of [mod_proxy_html](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html), such that we might avoid rewriting responses passing through the proxy? Essentially, to tell the application: Generate URIs/-Ls relative to this scheme/host/port, _instead_ of the application's values? Path would then seem like the odd one out, getting additional path components added which could already be handled in the reverse proxy configuration...

Reviewing the [docs](https://medusa-project.github.io/cantaloupe/manual/4.1/deployment.html#Reverse-Proxying), it reads like an oversight in the description: Proto, Host and Port all make reference to the _client_ request... this might be extended to the Path, as the "the client-facing base path of the application"?

**Comment by adolski** [comment]
Yeah, I agree with you. The above commit ought to take care of this.

**Comment by adam-vessey** [comment]
Just confirming: Yes, it appears to do the trick.

Thanks!
