### ISSUE TITLE
Kakadu will sometimes produce graysacle images

### ISSUE THREAD

**Issue by freost** [medusa-project/cantaloupe#281]
Hi,

We recently started using the KakaduNativeProcessor for our JP2 images and it has been working for most images but in some situations it produces graysacle output even though the source images is colored.

We talked to the guys at Kakadu Software and the images are valid JP2 and kdu_render produces color images as expected so they suggested that there's an issue with the implementation in cantaloupe.

I have attached a file that can be used for testing:

[example.jp2.zip](https://github.com/medusa-project/cantaloupe/files/3079718/example.jp2.zip)

**Comment by adolski** [comment]
Thanks for reporting this, @freost . The above commit ought to fix it.
