### ISSUE TITLE
Consistent release package naming

### ISSUE THREAD

**Issue by richardrodgers** [medusa-project/cantaloupe#38]
This is a very minor request, but the most recent release has changed the download path pattern from:

    ..../download/{version}/Cantaloupe-{version}.zip

to:

    ..../download/v{version}/Cantaloupe-{version}.zip

(the 'v' added). This makes automation tools, such as the one we are using:

    https://github.com/MITLibraries/docker-cantaloupe

more difficult to configure. Could there be a predictable/fixed pattern to release downloads?

**Comment by adolski** [comment]
Sorry about that. Releases will have the "v" prefix from now on.
