### ISSUE TITLE
Standalone binds to localhost and is not configurable

### ISSUE THREAD

**Issue by JPrevost** [medusa-project/cantaloupe#39]
Hi!

I'm trying to expose the standalone server to an external IP but this is blocking that:

https://github.com/medusa-project/cantaloupe/blob/b56ca1103a644fe99522df608a02c6da3d629f14/src/main/java/edu/illinois/library/cantaloupe/WebServer.java#L177

(It changed sometime after 2.2 fwiw)

It would be nice to see this changed to either:
`connector.setHost("0.0.0.0");`

Or if you want to allow for the option of not binding to every IP, a config option like how ports are configured would be great. Maybe `getHttpHost()` to match the similar `getHttpPort()`?

If this is something you agree should change, but don't have time to look at it please let me know how you'd prefer this to be handled and I can open a PR.

Thanks!

**Comment by adolski** [comment]
Thanks for looking into this -- I will try to take care of it soon (I like the idea of making it configurable) and schedule it for the next bugfix release.

**Comment by adolski** [comment]
There are now `http.host` and `https.host` keys available on the `develop` branch, if you are able to build a snapshot yourself (`mvn package -Dmaven.test.skip=true`). Otherwise, it will be available in a release soon.

**Comment by JPrevost** [comment]
This fully addressed my issue. Thanks so much for the super fast turnaround! 👍
