### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Eyal-R** [medusa-project/cantaloupe#42]
Hello,
Do you have some information on performance of the supported processors types (https://medusa-project.github.io/cantaloupe/manual/3.1/processors.html)?

Eyal

**Comment by adolski** [comment]
Hi,

Performance is discussed in general terms in the processor-specific sections of that page. There is also a bit more information in the [images section](https://medusa-project.github.io/cantaloupe/manual/3.1/images.html). But, that's all there is, for now.

This makes me wonder if a quick overview table detailing the expected performance of each processor with each source format would be helpful.

**Comment by Eyal-R** [comment]
Thanks a lot!
