### ISSUE TITLE
Bundled JRuby interpreter

### ISSUE THREAD

**Issue by Fredpitel** [medusa-project/cantaloupe#47]
Hello,
I wanted to clarify something I read in the 3.1 user manual for your application. In the delegate script section it mentions: "Delegate methods are implemented in Ruby, and invoked by a JRuby interpreter bundled into the image server." but I could never get it to work without manually installing JRuby on the server.

It seemed to be fine last week but now someone restarted our tomcat server and I'm getting the following error: 
javax.script.ScriptException: org.jruby.embed.EvalFailedException: (SyntaxError) /opt/jruby-9.1.5.0/lib/ruby/stdlib/net/http.rb:1070: syntax error, unexpected tDOTproxy_uri&.hostname

I noticed it's trying to use the JRuby library I installed and I was wondering if that could be the reason we're having issues. Is there a specific version of JRuby I should install instead?

Thanks for your help,
Fred

**Comment by adolski** [comment]
Hi Fred,

There shouldn't be any need to install JRuby separately. Do you know why the bundled JRuby wasn't working? Any error messages, etc.?

I've never tested with anything other than the bundled JRuby. Your other JRuby is a little bit newer than the one bundled into version 3.1, but i don't see why that would be a problem.

As for the ScriptException, it looks like there is a syntax error in your Ruby code. (Maybe after that last ampersand?)

**Comment by Fredpitel** [comment]
It couldn't recognize either "jruby" or "ruby" as a command.

The code works perfectly if I try it manually with "jruby delegates.rb" but something ends up not working when it's called through Java.

**Comment by adolski** [comment]
[Here is the line](https://github.com/jruby/jruby/blob/036ce39f0476d4bd718e23e64caff36bb50b8dbc/lib/ruby/stdlib/net/http.rb#L1070) in the standard library of your manually-installed JRuby (9.1.5.0) that is throwing the EvalFailedException. Note that this line is using Ruby 2.3 syntax, as this release is compatible with Ruby 2.3.

On the other hand, the version of JRuby bundled with Cantaloupe 3.1 is 9.0.5.0, which is only compatible up to Ruby 2.2.

My guess is that the JRuby you have installed separately is conflicting with the bundled JRuby. I would recommend either removing your custom JRuby, and going from there, or upgrading to Cantaloupe 3.2, which includes a 2.3-compatible JRuby., But really, the first option would be better.

Also note that Cantaloupe does not need or use the "ruby" or "jruby" commands. Instead it uses the Java [ScriptEngine](https://docs.oracle.com/javase/8/docs/api/javax/script/ScriptEngine.html) interface to invoke Ruby code.

**Comment by Fredpitel** [comment]
I'll try and make it work with the bundled interpreter although it seems it can't find the net/http library. I might have removed it while installing/uninstalling ruby manually on the server. Worst case I'll do a fresh install of Cantaloupe.

Thanks a bunch you've been very helpful.

**Comment by adolski** [comment]
Might have to add `require 'net/http'` to the script if it's not already there. Net::HTTP is part of the Ruby standard library which is definitely bundled in. Good luck!

**Comment by Fredpitel** [comment]
The require is actually what's throwing the error. I thought about it and it's probably juste the path variable that's messed up.

Thanks again I'll be closing this.
