### ISSUE TITLE
Resolve id of the file to path on the storage

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#59]
Hello, 
I want to resolve id of the file to path on the storage, can I use with HttpResolver ?
Input of my WS is id of the file that cantaloupe is sending and the output is path to the file,
what is the Content-Type need to be ?  (I tried with text/html;charset=UTF-8) but still getting error :

> 16:36:21.704 [qtp1349277854-14] INFO  e.i.l.c.resolver.HttpResolver - Resolved V1-FL7344049 to http://localhost:4242/NliWebServices/test/testUrlResolver/V1-FL7344049
> 16:36:22.825 [qtp1349277854-11] INFO  org.restlet.Component.WebApplication - Starting the internal HTTP client
> 16:36:22.835 [qtp1349277854-11] WARN  e.i.l.c.resolver.HttpResolver - Failed to determine source format (missing Content-Type at http://localhost:4242/NliWebServices/test/testUrlResolver/V1-FL7344049)

Thank you !

**Comment by adolski** [comment]
Hi, HttpResolver needs the web server to return a Content-Type header in the response. The Content-Type header must contain the media type (MIME type) of the image. So, if this is a JPEG image:

`http://localhost:4242/NliWebServices/test/testUrlResolver/V1-FL7344049`

Then the response would need to include a `Content-Type` header with a value of `image/jpeg`.

Hope that helps.

**Comment by adolski** [comment]
I think I misunderstood your question. HttpResolver is for serving images that reside on a web server via HTTP -- not looking up their paths. You want to instead be using FilesystemResolver with its ScriptStrategy:

    delegate_script.enabled = true
    delegate_script.pathname = delegates.rb
    resolver.static = FilesystemResolver
    FilesystemResolver.lookup_strategy = ScriptStrategy

Then in your delegates.rb file, you would need to implement the `get_pathname()` method, which will send a request to the web server to get the pathname. It would probably look something like this:

    def self.get_pathname(identifier)
      uri = 'http://localhost:4242/NliWebServices/test/testUrlResolver/' +
        CGI.escape(identifier)
      uri = URI.parse(uri)

      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)
      response = http.request(request)
      return nil if response.code.to_i >= 400

      # Here I am assuming that the response body will contain a pathname
      # if the image was found, and be empty if not.
      response.body.length > 0 ? response.body.strip : nil
    end

**Comment by prilia** [comment]
I think it need to be FilesystemResolver.lookup_strategy = ScriptLookupStrategy 
( not ScriptStrategy )

**Comment by prilia** [comment]
I get this error from ruby :
```
javax.script.ScriptException: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Cantaloupe::FilesystemResolver::CGI
	at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:104)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:93)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at edu.illinois.library.cantaloupe.script.RubyScriptEngine.invoke(RubyScriptEngi
```

**Comment by prilia** [comment]
Is it possible to cache the return value in case it's not nil ?

**Comment by adolski** [comment]
It's not currently possible because the delegate script is re-read upon each request -- so it's not possible to persist information across requests. That is a good idea for a feature, though.

**Comment by prilia** [comment]
Hi, 
Is it possible to add more data to this function : 
 module FilesystemResolver
    def self.get_pathname(identifier)
    end
 end

Like this in authorized function -> (identifier, full_size, operations, resulting_size,  output_format, request_uri, request_headers, client_ip, cookies)
We need these values ->request_uri, request_headers, client_ip, cookies
I don't sure about these -> full_size, operations, resulting_size,  output_format,
Maybe to add flag for insert it to the function or not ...

Thank you !

**Comment by adolski** [comment]
That isn't possible -- the idea is that the identifier in the URL always corresponds 1:1 with a source image.

Is this for authorization reasons? Like, you want to return `nil` if the `client_ip` is not allowed? If that is the case, you can just implement `authorized?()` and return `true` or `false`.

**Comment by prilia** [comment]
yes it's for security, 
is it possible to change `request_uri `in case no permissions while `authorized?()` function ?

**Comment by adolski** [comment]
I'm not sure what you mean. `request_uri` is the URI that the client is requesting, so there shouldn't be a need to change it.

**Comment by adolski** [comment]
Oh, you mean do an HTTP redirect? No, that's not possible, unfortunately... but it's another good idea.
