### ISSUE TITLE
Option to cache delegate method return values

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#60]
e.g. `delegate_script.cache_return_values`

**Comment by prilia** [comment]
Hi, it's grate that you add it to the this milestone !
Is it possible to add also TTL for caching ?
Thank you !

**Comment by adolski** [comment]
Yes, I think the cache would work with all delegate methods, for simplicity's sake. But the arguments would be cached as well, so there would only be a hit when arguments match.

It will be easy to do this kind of cache in memory. That might not be a good idea, though, as it will cause a gradual increase in memory usage and the cache will be cleared when the application is restarted.

An alternative would be to store the cache on the filesystem. Then it would be important to make sure that using the cache is not actually slower than calling delegate methods. 😄

Also, in 3.3, the delegate script state will persist across requests, so you will be able to implement your own custom caching in Ruby, if the built-in behavior doesn't meet your needs.

**Comment by adolski** [comment]
This is in place now on the `develop` branch.

* [New config keys](https://github.com/medusa-project/cantaloupe/blob/6848138bc47e5b99ecfa99a2631397ad1212ad8f/cantaloupe.properties.sample#L75-L80)
* [Documentation](https://github.com/medusa-project/cantaloupe/blob/6848138bc47e5b99ecfa99a2631397ad1212ad8f/website/manual/3.3/delegate-script.html#L46-L54)
