### ISSUE TITLE
Redirects from a delegate method

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#61]
Idea originating in #59.

One way to do this would be to allow some kind of non-boolean return value from `authorized?()`. Another would be to add a `redirect()` method with the same arguments as `authorized?()`.

**Comment by prilia** [comment]
The idea is like this:
In case NO authorization to see the picture the user will get thumbnail in low quality, 
to do this we need to change request OR change the size , region ...?

**Comment by adolski** [comment]
If you are able to build yourself a snapshot, you can now do this: https://github.com/medusa-project/cantaloupe/blob/develop/website/manual/3.3/access-control.html#L237-L250
