### ISSUE TITLE
Height, Width - maximum dynamic change user request

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#64]
Hi,
I have some question about changing HW of the image in early stage of user request:
For example : 
Image is very big h=5000, w=10000 and
case A - limit H
I want to limit maximum height be not more that 1024,
So the height need to be changed to 1024 and width to 512 ( because of proportion relative to h )

case B - limit W
Also we can do it with limit of width, in case not more that 1024,
So the width need to be changed to 1024 and height to 2048 ( because of proportion relative to w )

case C - limit H and W
we want to limit H,W to be not more than 1024
because in original values are w > h, so we'll use case A

So is it possible to add change request in early stage ?

**Comment by adolski** [comment]
Currently this is not possible.

I don't know about returning a different image than the one that is requested -- this might cause confusion for clients, and problems with caching reverse proxies. Will the upcoming redirect mechanism (#61) work for you, using a 303 redirect?

**Comment by adolski** [comment]
Tracking in #61
