### ISSUE TITLE
Uneven Intensity of tiles from ImageMagick -normalize operation

### ISSUE THREAD

**Issue by imoutsatsos** [medusa-project/cantaloupe#65]
The `normalize` operation has been added to ImageMagick as well as some of the other image processors. It is very convenient and facilitates browsing 16bit TIFF microscopy images without too much fuss! However, the tiles generated from this operation are of uneven intensity. See this example:
![image](https://cloud.githubusercontent.com/assets/3408226/20320272/5014ccc4-ab3f-11e6-880a-8cf8ebcd3888.png)

It would be great if the intensities were normalized first across the entire image and then applied to the tiles in a way that preserves their relative intensities. Not sure if this is possible but something to consider .

Thanks and best regards
Ioannis

**Comment by adolski** [comment]
Yes, normalization samples the darkest and brightest pixels and expands the contrast across the full 8-bit (output) range. This kind of unevenness will result when the darkest/brightest values vary across images. We probably need to use a histogram.

Would you be able to post those four source images so I can play with them?

**Comment by imoutsatsos** [comment]
The example above is a single image. Not four. Here is another example. Thank you for taking a look Alex
Best regards
Ioannis
![0a - 007 fld 1 wv fitc - fitc](https://cloud.githubusercontent.com/assets/3408226/20351920/29a83afe-abe3-11e6-9e59-d94c691afe7a.jpg)

**Comment by adolski** [comment]
Oh, I see. Yes, the sampling is done post-crop. It should really be done pre-crop, to preserve the intensity.

**Comment by adolski** [comment]
ImageMagickProcessor and GraphicsMagickProcessor now normalize before cropping. Haven't done any work on other processors yet though.
