### ISSUE TITLE
Caching - file does not exist error

### ISSUE THREAD

**Issue by FrancoisPaquette** [medusa-project/cantaloupe#66]
Hi,

We are getting this warning quite often, could you please tell me if you have seen it before and if so, what could be the cause?  

10:32:57.052 [Finalizer] [31mWARN [0;39m [36me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - edu.illinois.library.cantaloupe.cache.FilesystemCache$ConcurrentFileOutputStream.close(): Source '/var/cantaloupe/cache/image/67/9e/67/2719786_0%2C0%2C1769%2C2639_1769%2C.jpg.tmp' does not exist

It looks like OpenSea Dragon  might be involved because we only see it when it is used.

Thanks!
Frank

**Comment by adolski** [comment]
I'll take a closer look at it when I have time, but I'm pretty sure it's harmless. It happens shortly after the connection is closed during a cache write. I will see if there is anything I can do about it.
