### ISSUE TITLE
JAI Processor - missing library

### ISSUE THREAD

**Issue by FrancoisPaquette** [medusa-project/cantaloupe#86]
Hi,

We are getting this error from time to time, it looks like it's harmless though.

Error: Could not find mediaLib accelerator wrapper classes. Continuing in pure Java mode.
Occurs in: com.sun.media.jai.mlib.MediaLibAccessor
java.lang.NoClassDefFoundError: com/sun/medialib/mlib/Image

Here's how I'm able to recreate the error : 
- Restart the tomcat
- Request not the full size of the image, for example: f/2/o87_WMHhNSv0RHnC_vEctQ/full/200,/0/default.jpg.  
- The first image you will request after restarting the application server will create the error.

Looking at our log, the error is also happening after the config file is being reloaded but I was not able to recreate it that way.

Let me know if you need more information.

Thanks

**Comment by adolski** [comment]
Hi, that error is indeed harmless. It's coming from JAI. If you want, you can suppress it by adding the following VM option: `-Dcom.sun.media.jai.disableMediaLib=true`

A little bit more info (but not much) here: https://medusa-project.github.io/cantaloupe/manual/3.2/processors.html#JaiProcessor
