### ISSUE TITLE
Where to install gems

### ISSUE THREAD

**Issue by jweisman** [medusa-project/cantaloupe#98]
Hi there. Trying to figure out where to install gems to be used with delegate scripts. I've tried using the regular Ruby gem install and running it from a downloaded JRuby interpreter, but Cantaloupe always says it can't load the required files. Any help would be appreciated. Thanks.

**Comment by adolski** [comment]
Hi, the `gem env` command might be able to help. As long as your gem is installed in one of the gem paths (`$GEM_PATH`), and `require 'name-of-the-gem'` is called in the script, JRuby should be able to find and load it.

**Comment by jweisman** [comment]
Thanks for your answer. Adding the following snippet to the delegates.rb script:
```
require 'rubygems'
puts Gem.path
```

I was able to see that the path it was looking in was `~/.gem/jruby/2.3.0`. I installed my gems to there. I'm a bit nervous as it may be brittle when Cantaloupe upgrades its version of JRuby, but it works for now.

Thanks.
